// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::I64CO;
use proptest::prelude::*;

use crate::I64COSet;

#[inline]
pub(super) fn iv(start: i64, end_excl: i64) -> I64CO {
    I64CO::try_new(start, end_excl).unwrap()
}

#[inline]
pub(super) fn intervals(set: &I64COSet) -> &[I64CO] {
    set.intervals.as_ref()
}

#[inline]
pub(super) fn build<const N: usize>(pairs: [(i64, i64); N]) -> I64COSet {
    pairs
        .into_iter()
        .map(|(start, end)| iv(start, end))
        .collect()
}

/// Generates valid, non-empty intervals without enumerating the domain.
///
/// For code generation, replace `i64` and `I64CO` with the target primitive
/// and interval type.
pub(super) fn arb_iv() -> impl Strategy<Value = I64CO> {
    (any::<i64>(), any::<i64>()).prop_filter_map("interval endpoints must differ", |(a, b)| {
        let (start, end) = if a < b { (a, b) } else { (b, a) };
        I64CO::try_new(start, end)
    })
}
