// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod builder;
mod set;

mod test_support {
    use int_interval::I64CO;

    use proptest::prelude::*;

    #[inline]
    pub(super) fn iv(start: i64, end_excl: i64) -> I64CO {
        I64CO::try_new(start, end_excl).unwrap()
    }

    pub(super) const MID_VALUE: i64 = 0;

    pub(super) fn interval_pair() -> impl Strategy<Value = (i64, i64)> {
        (any::<i64>(), any::<i64>()).prop_filter_map("non-empty half-open interval", |(a, b)| {
            let start = a.min(b);
            let end_excl = a.max(b);

            (start < end_excl).then_some((start, end_excl))
        })
    }

    pub(super) fn build_from_vec(xs: Vec<(i64, i64)>) -> crate::I64COSet {
        let b = crate::I64COSetBuilder::new();

        for (start, end_excl) in xs {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
