// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use rayon::iter::{FromParallelIterator, IntoParallelIterator, ParallelIterator};

use crate::isize::funcs_for_canonicalization::{is_canonical, merge, normalize};

use super::*;

const BATCH_SIZE: usize = 128;

impl IsizeCOSet {
    /// Builds a set from an already canonical interval vector.
    ///
    /// # Safety
    ///
    /// The caller must guarantee that `intervals` is canonical:
    ///
    /// - intervals are sorted by ascending `start`;
    /// - intervals are non-overlapping;
    /// - contiguous intervals have already been merged;
    /// - therefore, for every adjacent pair `a, b`,
    ///   `a.end_excl() < b.start()` holds.
    ///
    /// Violating this invariant can make binary-search based queries
    /// return incorrect results.
    #[inline]
    pub(super) unsafe fn new_unchecked(intervals: Vec<IsizeCO>) -> Self {
        debug_assert!(is_canonical(&intervals));

        Self {
            intervals: Arc::from(intervals.into_boxed_slice()),
        }
    }
}

impl FromIterator<IsizeCO> for IsizeCOSet {
    fn from_iter<I>(iter: I) -> Self
    where
        I: IntoIterator<Item = IsizeCO>,
    {
        let mut batch = Vec::with_capacity(BATCH_SIZE);
        let mut reduced = Vec::new();

        for iv in iter {
            batch.push(iv);

            if batch.len() == BATCH_SIZE {
                let run = normalize(std::mem::replace(
                    &mut batch,
                    Vec::with_capacity(BATCH_SIZE),
                ));

                reduced = merge(reduced, run);
            }
        }

        if !batch.is_empty() {
            reduced = merge(reduced, normalize(batch));
        }

        // SAFETY:
        // Each normalized batch is canonical. `merge` preserves sorted,
        // non-overlapping, and non-adjacent interval invariants.
        unsafe { IsizeCOSet::new_unchecked(reduced) }
    }
}

impl FromParallelIterator<IsizeCO> for IsizeCOSet {
    fn from_par_iter<I>(iter: I) -> Self
    where
        I: IntoParallelIterator<Item = IsizeCO>,
    {
        let reduced = iter
            .into_par_iter()
            .fold(
                || (Vec::with_capacity(BATCH_SIZE), Vec::<IsizeCO>::new()),
                |(mut batch, mut reduced), iv| {
                    batch.push(iv);

                    if batch.len() == BATCH_SIZE {
                        let run = normalize(std::mem::replace(
                            &mut batch,
                            Vec::with_capacity(BATCH_SIZE),
                        ));

                        reduced = merge(reduced, run);
                    }

                    (batch, reduced)
                },
            )
            .map(|(batch, reduced)| {
                if batch.is_empty() {
                    reduced
                } else {
                    merge(reduced, normalize(batch))
                }
            })
            .reduce(Vec::new, merge);

        // SAFETY:
        // Every parallel fold result is canonical, and `merge` preserves the
        // canonical interval invariant during reduction.
        unsafe { IsizeCOSet::new_unchecked(reduced) }
    }
}

#[cfg(test)]
mod tests_for_from_iter;
#[cfg(test)]
mod tests_for_from_par_iter;
