// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::IsizeCO;
use proptest::prelude::*;

use crate::IsizeCOSet;

#[inline]
pub(super) fn iv(start: isize, end_excl: isize) -> IsizeCO {
    IsizeCO::try_new(start, end_excl).unwrap()
}

#[inline]
pub(super) fn intervals(set: &IsizeCOSet) -> &[IsizeCO] {
    set.intervals.as_ref()
}

#[inline]
pub(super) fn build<const N: usize>(pairs: [(isize, isize); N]) -> IsizeCOSet {
    pairs
        .into_iter()
        .map(|(start, end)| iv(start, end))
        .collect()
}

/// Generates valid, non-empty intervals without enumerating the domain.
///
/// For code generation, replace `isize` and `IsizeCO` with the target primitive
/// and interval type.
pub(super) fn arb_iv() -> impl Strategy<Value = IsizeCO> {
    (any::<isize>(), any::<isize>()).prop_filter_map("interval endpoints must differ", |(a, b)| {
        let (start, end) = if a < b { (a, b) } else { (b, a) };
        IsizeCO::try_new(start, end)
    })
}
