// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod builder;
mod set;

mod test_support {
    use int_interval::IsizeCO;

    use proptest::prelude::*;

    #[inline]
    pub(super) fn iv(start: isize, end_excl: isize) -> IsizeCO {
        IsizeCO::try_new(start, end_excl).unwrap()
    }

    pub(super) const MID_VALUE: isize = 0;

    pub(super) fn interval_pair() -> impl Strategy<Value = (isize, isize)> {
        (any::<isize>(), any::<isize>()).prop_filter_map("non-empty half-open interval", |(a, b)| {
            let start = a.min(b);
            let end_excl = a.max(b);

            (start < end_excl).then_some((start, end_excl))
        })
    }

    pub(super) fn build_from_vec(xs: Vec<(isize, isize)>) -> crate::IsizeCOSet {
        let b = crate::IsizeCOSetBuilder::new();

        for (start, end_excl) in xs {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
