// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use proptest::prelude::*;

use crate::{
    U32COSet,
    u32::test_support::{arb_iv, build, iv},
};

#[test]
fn union_inserts_into_empty_set() {
    let set = build([]);
    let query = iv(10, 20);

    assert_eq!(set.union_with_interval(query).as_slice(), &[query]);
}

#[test]
fn union_merges_intersecting_interval() {
    let set = build([(10, 20), (30, 40)]);
    let query = iv(15, 25);

    assert_eq!(
        set.union_with_interval(query).as_slice(),
        &[iv(10, 25), iv(30, 40)]
    );
}

#[test]
fn union_merges_adjacent_intervals() {
    let set = build([(10, 20), (30, 40)]);
    let query = iv(20, 30);

    assert_eq!(set.union_with_interval(query).as_slice(), &[iv(10, 40)]);
}

#[test]
fn union_inserts_disjoint_interval_without_removing_existing_intervals() {
    let set = build([(10, 20), (30, 40)]);
    let query = iv(22, 25);

    assert_eq!(
        set.union_with_interval(query).as_slice(),
        &[iv(10, 20), iv(22, 25), iv(30, 40)]
    );
}

#[test]
fn union_bridges_multiple_intervals() {
    let set = build([(0, 5), (10, 20), (30, 40), (50, 60)]);
    let query = iv(5, 50);

    assert_eq!(set.union_with_interval(query).as_slice(), &[iv(0, 60)]);
}

#[test]
fn union_returns_same_set_when_query_is_contained() {
    let set = build([(10, 20), (30, 40)]);
    let query = iv(12, 18);

    assert_eq!(set.union_with_interval(query), set);
}

#[test]
fn union_handles_domain_edges() {
    let set = build([(u32::MIN, u32::MIN + 1), (u32::MAX - 1, u32::MAX)]);
    let query = iv(u32::MIN + 1, u32::MAX - 1);

    assert_eq!(
        set.union_with_interval(query).as_slice(),
        &[iv(u32::MIN, u32::MAX)]
    );
}

proptest! {
    #[test]
    fn prop_union_matches_insert_then_canonicalize_reference_model(
        xs in prop::collection::vec(arb_iv(), 0..64),
        query in arb_iv(),
    ) {
        let set: U32COSet = xs.into_iter().collect();

        let expected: U32COSet = set
            .iter_intervals()
            .chain(std::iter::once(query))
            .collect();

        prop_assert_eq!(set.union_with_interval(query), expected);
    }

    #[test]
    fn prop_union_contains_query_and_all_source_intervals(
        xs in prop::collection::vec(arb_iv(), 0..64),
        query in arb_iv(),
    ) {
        let set: U32COSet = xs.into_iter().collect();
        let result = set.union_with_interval(query);

        prop_assert!(result.contains_interval(query));

        for interval in set.iter_intervals() {
            prop_assert!(result.contains_interval(interval));
        }
    }
}
