// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::U128CO;
use proptest::prelude::*;

use crate::U128COSet;

#[inline]
pub(super) fn iv(start: u128, end_excl: u128) -> U128CO {
    U128CO::try_new(start, end_excl).unwrap()
}

#[inline]
pub(super) fn intervals(set: &U128COSet) -> &[U128CO] {
    set.intervals.as_ref()
}

#[inline]
pub(super) fn build<const N: usize>(pairs: [(u128, u128); N]) -> U128COSet {
    pairs
        .into_iter()
        .map(|(start, end)| iv(start, end))
        .collect()
}

/// Generates valid, non-empty intervals without enumerating the domain.
///
/// For code generation, replace `u128` and `U128CO` with the target primitive
/// and interval type.
pub(super) fn arb_iv() -> impl Strategy<Value = U128CO> {
    (any::<u128>(), any::<u128>()).prop_filter_map("interval endpoints must differ", |(a, b)| {
        let (start, end) = if a < b { (a, b) } else { (b, a) };
        U128CO::try_new(start, end)
    })
}
