// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use super::*;

impl U16COSet {
    /// Returns the covered length inside `query`.
    ///
    /// Since `U16COSet` is canonical, all intersection segments are
    /// disjoint, so summing their lengths is valid.
    ///
    /// The result is always `<= query.len()`.
    #[inline]
    pub fn covered_len_of(&self, query: U16CO) -> usize {
        self.intersection_with_interval(query)
            .iter_intervals()
            .map(|iv| iv.len() as usize)
            .sum()
    }

    /// Returns the uncovered length inside `query`.
    #[inline]
    pub fn uncovered_len_of(&self, query: U16CO) -> usize {
        query.len() as usize - self.covered_len_of(query)
    }

    /// Returns `covered_len(query) / query.len()` as `f32`.
    ///
    /// `query.len()` is non-zero because `U16CO` cannot represent an
    /// empty interval.
    #[inline]
    pub fn coverage_ratio_of(&self, query: U16CO) -> f32 {
        self.covered_len_of(query) as f32 / query.len() as f32
    }
}

#[cfg(test)]
mod tests;
