// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::U16CO;
use proptest::prelude::*;

use crate::U16COSet;

#[inline]
pub(super) fn iv(start: u16, end_excl: u16) -> U16CO {
    U16CO::try_new(start, end_excl).unwrap()
}

#[inline]
pub(super) fn intervals(set: &U16COSet) -> &[U16CO] {
    set.intervals.as_ref()
}

#[inline]
pub(super) fn build<const N: usize>(pairs: [(u16, u16); N]) -> U16COSet {
    pairs
        .into_iter()
        .map(|(start, end)| iv(start, end))
        .collect()
}

/// Generates valid, non-empty intervals without enumerating the domain.
///
/// For code generation, replace `u16` and `U16CO` with the target primitive
/// and interval type.
pub(super) fn arb_iv() -> impl Strategy<Value = U16CO> {
    (any::<u16>(), any::<u16>()).prop_filter_map("interval endpoints must differ", |(a, b)| {
        let (start, end) = if a < b { (a, b) } else { (b, a) };
        U16CO::try_new(start, end)
    })
}
