// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod basic;
mod coverage;
mod predicate;
mod search;

mod test_support {
    use crate::{I16COSetBuilder, i16::tests::test_support::iv};

    pub(super) fn build<const N: usize>(intervals: [(i16, i16); N]) -> crate::I16COSet {
        let b = I16COSetBuilder::new();

        for (start, end_excl) in intervals {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
