// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod basic;
mod coverage;
mod predicate;
mod search;

mod test_support {
    use crate::{I64COSetBuilder, i64::tests::test_support::iv};

    pub(super) fn build<const N: usize>(intervals: [(i64, i64); N]) -> crate::I64COSet {
        let b = I64COSetBuilder::new();

        for (start, end_excl) in intervals {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
