// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod basic;
mod coverage;
mod predicate;
mod search;

mod test_support {
    use crate::{I128COSetBuilder, i128::tests::test_support::iv};

    pub(super) fn build<const N: usize>(intervals: [(i128, i128); N]) -> crate::I128COSet {
        let b = I128COSetBuilder::new();

        for (start, end_excl) in intervals {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
