// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use proptest::prelude::*;

use crate::{
    U16COSet,
    u16::test_support::{arb_iv, build, iv},
};

#[test]
fn difference_of_empty_set_is_empty() {
    let set = build([]);
    let query = iv(10, 20);

    assert!(set.difference_with_interval(query).is_empty());
}

#[test]
fn difference_with_disjoint_query_returns_same_set() {
    let set = build([(10, 20), (30, 40)]);
    let query = iv(20, 30);

    assert_eq!(set.difference_with_interval(query), set);
}

#[test]
fn difference_with_adjacent_query_returns_same_set() {
    let set = build([(10, 20), (30, 40)]);

    assert_eq!(set.difference_with_interval(iv(0, 10)), set);
    assert_eq!(set.difference_with_interval(iv(20, 30)), set);
    assert_eq!(set.difference_with_interval(iv(40, 50)), set);
}

#[test]
fn difference_removes_fully_covered_interval() {
    let set = build([(10, 20), (30, 40), (50, 60)]);
    let query = iv(25, 45);

    assert_eq!(
        set.difference_with_interval(query).as_slice(),
        &[iv(10, 20), iv(50, 60)]
    );
}

#[test]
fn difference_clips_left_side_of_intersecting_interval() {
    let set = build([(10, 20), (30, 40)]);
    let query = iv(5, 15);

    assert_eq!(
        set.difference_with_interval(query).as_slice(),
        &[iv(15, 20), iv(30, 40)]
    );
}

#[test]
fn difference_clips_right_side_of_intersecting_interval() {
    let set = build([(10, 20), (30, 40)]);
    let query = iv(15, 25);

    assert_eq!(
        set.difference_with_interval(query).as_slice(),
        &[iv(10, 15), iv(30, 40)]
    );
}

#[test]
fn difference_splits_single_interval_when_query_is_inside() {
    let set = build([(10, 40)]);
    let query = iv(15, 25);

    assert_eq!(
        set.difference_with_interval(query).as_slice(),
        &[iv(10, 15), iv(25, 40)]
    );
}

#[test]
fn difference_removes_middle_hits_and_clips_boundary_hits() {
    let set = build([(0, 10), (20, 30), (40, 50), (60, 70)]);
    let query = iv(5, 65);

    assert_eq!(
        set.difference_with_interval(query).as_slice(),
        &[iv(0, 5), iv(65, 70)]
    );
}

#[test]
fn difference_removes_everything_when_query_contains_set() {
    let set = build([(10, 20), (30, 40), (50, 60)]);
    let query = iv(0, 70);

    assert!(set.difference_with_interval(query).is_empty());
}

#[test]
fn difference_uses_canonical_source_intervals() {
    let set = build([(0, 5), (5, 10), (12, 20), (18, 30)]);
    let query = iv(8, 15);

    assert_eq!(set.as_slice(), &[iv(0, 10), iv(12, 30)]);
    assert_eq!(
        set.difference_with_interval(query).as_slice(),
        &[iv(0, 8), iv(15, 30)]
    );
}

#[test]
fn difference_handles_domain_edges() {
    let set = build([(u16::MIN, u16::MIN + 10), (u16::MAX - 10, u16::MAX)]);

    assert_eq!(
        set.difference_with_interval(iv(u16::MIN, u16::MIN + 5))
            .as_slice(),
        &[iv(u16::MIN + 5, u16::MIN + 10), iv(u16::MAX - 10, u16::MAX)]
    );

    assert_eq!(
        set.difference_with_interval(iv(u16::MAX - 5, u16::MAX))
            .as_slice(),
        &[iv(u16::MIN, u16::MIN + 10), iv(u16::MAX - 10, u16::MAX - 5)]
    );
}

proptest! {
    #[test]
    fn prop_difference_matches_pointwise_reference_model(
        xs in prop::collection::vec(arb_iv(), 0..64),
        query in arb_iv(),
    ) {
        let set: U16COSet = xs.into_iter().collect();

        let expected: U16COSet = set
            .iter_intervals()
            .flat_map(|interval| match interval.difference(query) {
                int_interval::ZeroOneTwo::Zero => Vec::new(),
                int_interval::ZeroOneTwo::One(x) => vec![x],
                int_interval::ZeroOneTwo::Two(x, y) => vec![x, y],
            })
            .collect();

        prop_assert_eq!(set.difference_with_interval(query), expected);
    }

    #[test]
    fn prop_difference_results_do_not_intersect_query(
        xs in prop::collection::vec(arb_iv(), 0..64),
        query in arb_iv(),
    ) {
        let set: U16COSet = xs.into_iter().collect();
        let result = set.difference_with_interval(query);

        for interval in result.iter_intervals() {
            prop_assert!(!interval.intersects(query));
        }
    }

    #[test]
    fn prop_difference_preserves_points_outside_query(
        xs in prop::collection::vec(arb_iv(), 0..64),
        query in arb_iv(),
        x in any::<u16>(),
    ) {
        let set: U16COSet = xs.into_iter().collect();
        let result = set.difference_with_interval(query);

        prop_assert_eq!(
            result.contains_point(x),
            set.contains_point(x) && !query.contains(x)
        );
    }
}
