mod signed;
mod unsigned;

use std::{fs, path::Path};

const TEMPLATE_UNSIGNED_FILE: &str = "u8.rs";
const TEMPLATE_UNSIGNED_DIR: &str = "u8";

const TEMPLATE_SIGNED_FILE: &str = "i8.rs";
const TEMPLATE_SIGNED_DIR: &str = "i8";

const GENERATED_WARNING_BATCH_MOD: &str = "\
// -----------------------------------------------------------------------------\n\
// @generated by xtask/codegen (--batch)\n\
// DO NOT EDIT MANUALLY.\n\
// Changes will be overwritten.\n\
// -----------------------------------------------------------------------------\n\n";

pub fn generate_unsigned(src: &Path) {
    let batch_src = src.join("batch");
    let template = fs::read_to_string(batch_src.join(TEMPLATE_UNSIGNED_FILE)).unwrap();

    for (dst_ty, dst_interval_name, dst_set_name) in unsigned::TYPES {
        generate_unsigned_type(
            &batch_src,
            &template,
            dst_ty,
            dst_interval_name,
            dst_set_name,
        );
        generate_unsigned_tests(&batch_src, dst_ty, dst_interval_name, dst_set_name);
    }
}

pub fn generate_signed(src: &Path) {
    let batch_src = src.join("batch");
    let template = fs::read_to_string(batch_src.join(TEMPLATE_SIGNED_FILE)).unwrap();

    for (dst_ty, dst_interval_name, dst_len_ty, dst_set_name) in signed::TYPES {
        generate_signed_type(
            &batch_src,
            &template,
            dst_ty,
            dst_interval_name,
            dst_len_ty,
            dst_set_name,
        );
        generate_signed_tests(
            &batch_src,
            dst_ty,
            dst_interval_name,
            dst_len_ty,
            dst_set_name,
        );
    }
}

pub fn write_batch_mod(src: &Path) {
    let mut s = String::new();

    s.push_str(GENERATED_WARNING_BATCH_MOD);

    s.push_str("mod u8;\n");
    for (ty, _, _) in unsigned::TYPES {
        s.push_str(&format!("mod {ty};\n"));
    }

    s.push_str("mod i8;\n");
    for (ty, _, _, _) in signed::TYPES {
        s.push_str(&format!("mod {ty};\n"));
    }

    s.push('\n');

    s.push_str("pub use u8::U8COBatchSet;\n");
    for (ty, _, set_name) in unsigned::TYPES {
        s.push_str(&format!("pub use {ty}::{set_name};\n"));
    }

    s.push_str("pub use i8::I8COBatchSet;\n");
    for (ty, _, _, set_name) in signed::TYPES {
        s.push_str(&format!("pub use {ty}::{set_name};\n"));
    }

    fs::write(src.join("batch.rs"), s).unwrap();
}

fn generate_unsigned_type(
    batch_src: &Path,
    template: &str,
    dst_ty: &str,
    dst_interval_name: &str,
    dst_set_name: &str,
) {
    let body = unsigned::replace_batch(template, dst_ty, dst_interval_name, dst_set_name);
    let code = format!("{}{}", unsigned::GENERATED_WARNING_BATCH, body);
    fs::write(batch_src.join(format!("{dst_ty}.rs")), code).unwrap();
}

fn generate_signed_type(
    batch_src: &Path,
    template: &str,
    dst_ty: &str,
    dst_interval_name: &str,
    dst_len_ty: &str,
    dst_set_name: &str,
) {
    let body = signed::replace_batch(
        template,
        dst_ty,
        dst_interval_name,
        dst_len_ty,
        dst_set_name,
    );
    let code = format!("{}{}", signed::GENERATED_WARNING_BATCH, body);
    fs::write(batch_src.join(format!("{dst_ty}.rs")), code).unwrap();
}

fn generate_unsigned_tests(
    batch_src: &Path,
    dst_ty: &str,
    dst_interval_name: &str,
    dst_set_name: &str,
) {
    let src_tests = batch_src.join(TEMPLATE_UNSIGNED_DIR);
    let dst_tests = batch_src.join(dst_ty);

    reset_dir(&dst_tests);

    for path in sorted_files(&src_tests) {
        let text = fs::read_to_string(&path).unwrap();
        let body = unsigned::replace_batch(&text, dst_ty, dst_interval_name, dst_set_name);
        let code = format!("{}{}", unsigned::GENERATED_WARNING_BATCH, body);
        fs::write(dst_tests.join(path.file_name().unwrap()), code).unwrap();
    }
}

fn generate_signed_tests(
    batch_src: &Path,
    dst_ty: &str,
    dst_interval_name: &str,
    dst_len_ty: &str,
    dst_set_name: &str,
) {
    let src_tests = batch_src.join(TEMPLATE_SIGNED_DIR);
    let dst_tests = batch_src.join(dst_ty);

    reset_dir(&dst_tests);

    for path in sorted_files(&src_tests) {
        let text = fs::read_to_string(&path).unwrap();
        let body =
            signed::replace_batch(&text, dst_ty, dst_interval_name, dst_len_ty, dst_set_name);
        let code = format!("{}{}", signed::GENERATED_WARNING_BATCH, body);
        fs::write(dst_tests.join(path.file_name().unwrap()), code).unwrap();
    }
}

fn reset_dir(path: &Path) {
    if path.exists() {
        fs::remove_dir_all(path).unwrap();
    }
    fs::create_dir_all(path).unwrap();
}

fn sorted_files(dir: &Path) -> Vec<std::path::PathBuf> {
    let mut xs = fs::read_dir(dir)
        .unwrap()
        .map(|e| e.unwrap().path())
        .filter(|p| p.is_file())
        .collect::<Vec<_>>();

    xs.sort();
    xs
}
