use super::*;

const TEMPLATE_TY: &str = "u8";
const TEMPLATE_UPPER: &str = "U8";

const TARGETS: &[Ty] = &[
    Ty::new("i8", "I8"),
    Ty::new("u16", "U16"),
    Ty::new("i16", "I16"),
    Ty::new("u32", "U32"),
    Ty::new("i32", "I32"),
    Ty::new("u64", "U64"),
    Ty::new("i64", "I64"),
    Ty::new("u128", "U128"),
    Ty::new("i128", "I128"),
    Ty::new("usize", "Usize"),
    Ty::new("isize", "Isize"),
];

#[derive(Copy, Clone, Debug)]
struct Ty {
    lower: &'static str,
    upper: &'static str,
}

impl Ty {
    const fn new(lower: &'static str, upper: &'static str) -> Self {
        Self { lower, upper }
    }

    fn set_name(self) -> String {
        format!("{}COSet", self.upper)
    }
}

pub(super) fn codegen(mode: CodegenMode) -> Result<(), Box<dyn std::error::Error>> {
    let repo = repo_root()?;
    let src = repo.join(SRC_ROOT);

    ensure_template_exists(&src, TEMPLATE_TY)?;

    for ty in TARGETS {
        generate_root_module(
            &src,
            TEMPLATE_TY,
            ty.lower,
            *ty,
            rewrite_tokens,
            GENERATED_FILE_NOTICE,
            mode,
        )?;

        generate_test_tree(
            &src,
            TEMPLATE_TY,
            ty.lower,
            *ty,
            rewrite_tokens,
            GENERATED_FILE_NOTICE,
            mode,
        )?;
    }

    update_generated_lib_rs(&src, &generated_lib_block(), mode)?;

    Ok(())
}

fn rewrite_tokens(src: &str, ty: Ty) -> String {
    src.replace(TEMPLATE_UPPER, ty.upper)
        .replace(TEMPLATE_TY, ty.lower)
}

fn generated_lib_block() -> String {
    let mut lines = Vec::new();

    lines.push(INTEGER_LIB_BLOCK_START.to_string());
    lines.push(format!("// This block is generated by `{RUN_CMD}`."));
    lines.push("// Do not edit manually.".to_string());

    for ty in TARGETS {
        lines.push(format!("mod {};", ty.lower));
    }

    lines.push(String::new());

    for ty in TARGETS {
        lines.push(format!("pub use {}::{};", ty.lower, ty.set_name()));
    }

    lines.push(INTEGER_LIB_BLOCK_END.to_string());
    lines.join("\n")
}
