mod signed;
mod unsigned;

use std::{
    env, fs, io,
    path::{Path, PathBuf},
};

const SRC_ROOT: &str = "src";

const COMMAND_UNSIGNED: &str = "--unsigned";
const COMMAND_SIGNED: &str = "--signed";
const COMMAND_CHECK: &str = "--check";

const RUN_UNSIGNED_CMD: &str = "cargo run -p codegen -- --unsigned";
const RUN_UNSIGNED_CHECK_CMD: &str = "cargo run -p codegen -- --unsigned --check";

const RUN_SIGNED_CMD: &str = "cargo run -p codegen -- --signed";
const RUN_SIGNED_CHECK_CMD: &str = "cargo run -p codegen -- --signed --check";

const GENERATED_FILE_NOTICE_UNSIGNED: &str = "\
// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
// -----------------------------------------------------------------------------

";

const GENERATED_FILE_NOTICE_SIGNED: &str = "\
// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

";

const UNSIGNED_LIB_BLOCK_START: &str = "// codegen:unsigned:start";
const UNSIGNED_LIB_BLOCK_END: &str = "// codegen:unsigned:end";

const SIGNED_LIB_BLOCK_START: &str = "// codegen:signed:start";
const SIGNED_LIB_BLOCK_END: &str = "// codegen:signed:end";

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
enum CodegenMode {
    Write,
    Check,
}

impl CodegenMode {
    #[inline]
    fn is_check(self) -> bool {
        matches!(self, Self::Check)
    }
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = env::args().skip(1).collect::<Vec<_>>();

    match args.as_slice() {
        [flag] if flag == COMMAND_UNSIGNED => unsigned::codegen(CodegenMode::Write)?,
        [flag, check] if flag == COMMAND_UNSIGNED && check == COMMAND_CHECK => {
            unsigned::codegen(CodegenMode::Check)?
        }

        [flag] if flag == COMMAND_SIGNED => signed::codegen(CodegenMode::Write)?,
        [flag, check] if flag == COMMAND_SIGNED && check == COMMAND_CHECK => {
            signed::codegen(CodegenMode::Check)?
        }

        _ => {
            eprintln!("usage:");
            eprintln!("  {RUN_UNSIGNED_CMD}");
            eprintln!("  {RUN_UNSIGNED_CHECK_CMD}");
            eprintln!("  {RUN_SIGNED_CMD}");
            eprintln!("  {RUN_SIGNED_CHECK_CMD}");
            std::process::exit(2);
        }
    }

    Ok(())
}

fn repo_root() -> io::Result<PathBuf> {
    let cwd = env::current_dir()?;

    if cwd.join(SRC_ROOT).is_dir() {
        return Ok(cwd);
    }

    if let Some(parent) = cwd.parent().and_then(Path::parent) {
        if parent.join(SRC_ROOT).is_dir() {
            return Ok(parent.to_path_buf());
        }
    }

    Err(io::Error::new(
        io::ErrorKind::NotFound,
        format!("cannot find repository root containing ./{SRC_ROOT}"),
    ))
}

fn ensure_template_exists(src: &Path, template_ty: &str) -> io::Result<()> {
    let root_template = src.join(format!("{template_ty}.rs"));
    let test_template = src.join(template_ty);

    if !root_template.is_file() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("missing template file: {}", root_template.display()),
        ));
    }

    if !test_template.is_dir() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("missing template dir: {}", test_template.display()),
        ));
    }

    Ok(())
}

fn generate_root_module<T>(
    src: &Path,
    template_ty: &str,
    target_lower: &str,
    ty: T,
    rewrite: fn(&str, T) -> String,
    notice: &str,
    mode: CodegenMode,
) -> io::Result<()>
where
    T: Copy,
{
    let from = src.join(format!("{template_ty}.rs"));
    let to = src.join(format!("{target_lower}.rs"));
    copy_rs_file_with_rewrite(&from, &to, ty, rewrite, notice, mode)
}

fn generate_test_tree<T>(
    src: &Path,
    template_ty: &str,
    target_lower: &str,
    ty: T,
    rewrite: fn(&str, T) -> String,
    notice: &str,
    mode: CodegenMode,
) -> io::Result<()>
where
    T: Copy,
{
    let from_dir = src.join(template_ty);
    let to_dir = src.join(target_lower);

    if mode == CodegenMode::Write && to_dir.exists() {
        fs::remove_dir_all(&to_dir)?;
    }

    copy_dir_with_rewrite(&from_dir, &to_dir, ty, rewrite, notice, mode)
}

fn copy_dir_with_rewrite<T>(
    from_dir: &Path,
    to_dir: &Path,
    ty: T,
    rewrite: fn(&str, T) -> String,
    notice: &str,
    mode: CodegenMode,
) -> io::Result<()>
where
    T: Copy,
{
    if mode == CodegenMode::Write {
        fs::create_dir_all(to_dir)?;
    }

    for entry in fs::read_dir(from_dir)? {
        let entry = entry?;
        let from_path = entry.path();
        let to_path = to_dir.join(entry.file_name());

        if from_path.is_dir() {
            copy_dir_with_rewrite(&from_path, &to_path, ty, rewrite, notice, mode)?;
        } else if from_path.extension().is_some_and(|ext| ext == "rs") {
            copy_rs_file_with_rewrite(&from_path, &to_path, ty, rewrite, notice, mode)?;
        } else if mode == CodegenMode::Write {
            if let Some(parent) = to_path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::copy(&from_path, &to_path)?;
        } else {
            check_file_equal(&from_path, &to_path)?;
        }
    }

    Ok(())
}

fn copy_rs_file_with_rewrite<T>(
    from: &Path,
    to: &Path,
    ty: T,
    rewrite: fn(&str, T) -> String,
    notice: &str,
    mode: CodegenMode,
) -> io::Result<()>
where
    T: Copy,
{
    let src = fs::read_to_string(from)?;
    let expected = format!("{notice}{}", rewrite(&src, ty));

    write_or_check_text(to, &expected, mode)
}

fn update_lib_rs(
    src: &Path,
    start: &str,
    end: &str,
    block: &str,
    mode: CodegenMode,
) -> io::Result<()> {
    let path = src.join("lib.rs");
    let old = fs::read_to_string(&path)?;

    let expected = match replace_marked_block(&old, start, end, block) {
        Some(x) => x,
        None => append_marked_block(&old, block),
    };

    write_or_check_text(&path, &expected, mode)
}

fn write_or_check_text(path: &Path, expected: &str, mode: CodegenMode) -> io::Result<()> {
    if mode.is_check() {
        let actual = fs::read_to_string(path).map_err(|err| {
            io::Error::new(
                err.kind(),
                format!(
                    "generated file is missing or unreadable: {}",
                    path.display()
                ),
            )
        })?;

        if actual != expected {
            return Err(io::Error::other(format!(
                "generated file is stale: {}\nrun codegen and commit the result",
                path.display()
            )));
        }

        return Ok(());
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }

    fs::write(path, expected)
}

fn check_file_equal(expected_from: &Path, actual_to: &Path) -> io::Result<()> {
    let expected = fs::read(expected_from)?;
    let actual = fs::read(actual_to).map_err(|err| {
        io::Error::new(
            err.kind(),
            format!(
                "generated file is missing or unreadable: {}",
                actual_to.display()
            ),
        )
    })?;

    if expected != actual {
        return Err(io::Error::other(format!(
            "generated file is stale: {}\nrun codegen and commit the result",
            actual_to.display()
        )));
    }

    Ok(())
}

fn replace_marked_block(
    old: &str,
    start_marker: &str,
    end_marker: &str,
    new_block: &str,
) -> Option<String> {
    let start = old.find(start_marker)?;
    let after_start = start + start_marker.len();
    let rel_end = old[after_start..].find(end_marker)?;
    let end = after_start + rel_end + end_marker.len();

    let mut out = String::with_capacity(old.len() + new_block.len());
    out.push_str(&old[..start]);
    out.push_str(new_block);
    out.push_str(&old[end..]);
    Some(out)
}

fn append_marked_block(old: &str, block: &str) -> String {
    let mut out = old.trim_end().to_string();
    out.push_str("\n\n");
    out.push_str(block);
    out.push('\n');
    out
}
