use super::*;

const TEMPLATE_SIGNED_TY: &str = "i8";
const TEMPLATE_SIGNED_UPPER: &str = "I8";
const TEMPLATE_UNSIGNED_TY: &str = "u8";

const TARGETS: &[Ty] = &[
    Ty::new("i16", "I16", "u16"),
    Ty::new("i32", "I32", "u32"),
    Ty::new("i64", "I64", "u64"),
    Ty::new("i128", "I128", "u128"),
    Ty::new("isize", "Isize", "usize"),
];

#[derive(Copy, Clone, Debug)]
struct Ty {
    signed_lower: &'static str,
    signed_upper: &'static str,
    unsigned_lower: &'static str,
}

impl Ty {
    const fn new(
        signed_lower: &'static str,
        signed_upper: &'static str,
        unsigned_lower: &'static str,
    ) -> Self {
        Self {
            signed_lower,
            signed_upper,
            unsigned_lower,
        }
    }

    fn set_name(self) -> String {
        format!("{}COSet", self.signed_upper)
    }

    fn builder_name(self) -> String {
        format!("{}COSetBuilder", self.signed_upper)
    }
}

pub(super) fn codegen(mode: CodegenMode) -> Result<(), Box<dyn std::error::Error>> {
    let repo = repo_root()?;
    let src = repo.join(SRC_ROOT);

    ensure_template_exists(&src, TEMPLATE_SIGNED_TY)?;

    for ty in TARGETS {
        generate_root_module(
            &src,
            TEMPLATE_SIGNED_TY,
            ty.signed_lower,
            *ty,
            rewrite_tokens,
            GENERATED_FILE_NOTICE_SIGNED,
            mode,
        )?;

        generate_test_tree(
            &src,
            TEMPLATE_SIGNED_TY,
            ty.signed_lower,
            *ty,
            rewrite_tokens,
            GENERATED_FILE_NOTICE_SIGNED,
            mode,
        )?;
    }

    update_lib_rs(
        &src,
        SIGNED_LIB_BLOCK_START,
        SIGNED_LIB_BLOCK_END,
        &generated_lib_block(),
        mode,
    )?;

    Ok(())
}

fn rewrite_tokens(src: &str, ty: Ty) -> String {
    src.replace(TEMPLATE_SIGNED_UPPER, ty.signed_upper)
        .replace(TEMPLATE_SIGNED_TY, ty.signed_lower)
        .replace(TEMPLATE_UNSIGNED_TY, ty.unsigned_lower)
}

fn generated_lib_block() -> String {
    let mut lines = Vec::new();

    lines.push(SIGNED_LIB_BLOCK_START.to_string());
    lines.push(format!("// This block is generated by `{RUN_SIGNED_CMD}`."));
    lines.push("// Do not edit manually.".to_string());

    for ty in TARGETS {
        lines.push(format!("mod {};", ty.signed_lower));
    }

    lines.push(String::new());

    for ty in TARGETS {
        lines.push(format!(
            "pub use {}::builder::{};",
            ty.signed_lower,
            ty.builder_name()
        ));
        lines.push(format!(
            "pub use {}::set::{};",
            ty.signed_lower,
            ty.set_name()
        ));
    }

    lines.push(SIGNED_LIB_BLOCK_END.to_string());
    lines.join("\n")
}
