// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use proptest::prelude::*;

use crate::{
    U128COSet,
    u128::test_support::{arb_iv, build, iv},
};

#[test]
fn difference_of_empty_set_is_empty() {
    let empty = build([]);
    let other = build([(10, 20)]);

    assert!(empty.difference_with_set(&other).is_empty());
}

#[test]
fn difference_with_empty_set_returns_source_set() {
    let set = build([(10, 20), (30, 40)]);
    let empty = build([]);

    assert_eq!(set.difference_with_set(&empty), set);
}

#[test]
fn difference_with_disjoint_set_returns_source_content() {
    let left = build([(10, 20), (30, 40)]);
    let right = build([(0, 10), (20, 30), (40, 50)]);

    assert_eq!(left.difference_with_set(&right), left);
}

#[test]
fn difference_removes_fully_covered_intervals() {
    let left = build([(10, 20), (30, 40), (50, 60)]);
    let right = build([(5, 45), (48, 70)]);

    assert!(left.difference_with_set(&right).is_empty());
}

#[test]
fn difference_clips_boundary_intervals() {
    let left = build([(10, 20), (30, 40), (50, 60)]);
    let right = build([(15, 35), (55, 70)]);

    assert_eq!(
        left.difference_with_set(&right).as_slice(),
        &[iv(10, 15), iv(35, 40), iv(50, 55)]
    );
}

#[test]
fn difference_splits_one_source_interval_multiple_times() {
    let left = build([(0, 100)]);
    let right = build([(10, 20), (30, 40), (50, 60)]);

    assert_eq!(
        left.difference_with_set(&right).as_slice(),
        &[iv(0, 10), iv(20, 30), iv(40, 50), iv(60, 100)]
    );
}

#[test]
fn difference_reuses_long_removing_interval_across_source_intervals() {
    let left = build([(0, 10), (20, 30), (40, 50)]);
    let right = build([(5, 45)]);

    assert_eq!(
        left.difference_with_set(&right).as_slice(),
        &[iv(0, 5), iv(45, 50)]
    );
}

#[test]
fn difference_removes_identical_set() {
    let set = build([(10, 20), (30, 40), (50, 60)]);

    assert!(set.difference_with_set(&set).is_empty());
}

#[test]
fn difference_uses_canonical_source_intervals() {
    let left = build([(0, 5), (5, 10), (20, 25), (24, 30)]);
    let right = build([(3, 8), (8, 22)]);

    assert_eq!(left.as_slice(), &[iv(0, 10), iv(20, 30)]);
    assert_eq!(right.as_slice(), &[iv(3, 22)]);
    assert_eq!(
        left.difference_with_set(&right).as_slice(),
        &[iv(0, 3), iv(22, 30)]
    );
}

#[test]
fn difference_handles_domain_edges() {
    let left = build([(u128::MIN, u128::MIN + 10), (u128::MAX - 10, u128::MAX)]);
    let right = build([(u128::MIN, u128::MIN + 5), (u128::MAX - 5, u128::MAX)]);

    assert_eq!(
        left.difference_with_set(&right).as_slice(),
        &[iv(u128::MIN + 5, u128::MIN + 10), iv(u128::MAX - 10, u128::MAX - 5)]
    );
}

proptest! {
    #[test]
    fn prop_difference_matches_pointwise_membership(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
        x in any::<u128>(),
    ) {
        let left: U128COSet = xs.into_iter().collect();
        let right: U128COSet = ys.into_iter().collect();
        let result = left.difference_with_set(&right);

        prop_assert_eq!(
            result.contains_point(x),
            left.contains_point(x) && !right.contains_point(x)
        );
    }

    #[test]
    fn prop_difference_is_disjoint_from_removed_set(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: U128COSet = xs.into_iter().collect();
        let right: U128COSet = ys.into_iter().collect();
        let result = left.difference_with_set(&right);

        prop_assert!(
            result.intersection_with_set(&right).is_empty()
        );
    }

    #[test]
    fn prop_difference_is_contained_by_source_set(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: U128COSet = xs.into_iter().collect();
        let right: U128COSet = ys.into_iter().collect();
        let result = left.difference_with_set(&right);

        for interval in result.iter_intervals() {
            prop_assert!(left.contains_interval(interval));
        }
    }

    #[test]
    fn prop_difference_matches_repeated_interval_removal_reference_model(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: U128COSet = xs.into_iter().collect();
        let right: U128COSet = ys.into_iter().collect();

        let expected = right
            .iter_intervals()
            .fold(left.clone(), |set, interval| {
                set.difference_with_interval(interval)
            });

        prop_assert_eq!(left.difference_with_set(&right), expected);
    }
}
