// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod basic;
mod coverage;
mod predicate;
mod search;

mod test_support {
    use crate::{IsizeCOSetBuilder, isize::tests::test_support::iv};

    pub(super) fn build<const N: usize>(intervals: [(isize, isize); N]) -> crate::IsizeCOSet {
        let b = IsizeCOSetBuilder::new();

        for (start, end_excl) in intervals {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
