// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod builder;
mod set;

mod test_support {
    use int_interval::I16CO;

    use proptest::prelude::*;

    #[inline]
    pub(super) fn iv(start: i16, end_excl: i16) -> I16CO {
        I16CO::try_new(start, end_excl).unwrap()
    }

    pub(super) const MID_VALUE: i16 = 0;

    pub(super) fn interval_pair() -> impl Strategy<Value = (i16, i16)> {
        (any::<i16>(), any::<i16>()).prop_filter_map("non-empty half-open interval", |(a, b)| {
            let start = a.min(b);
            let end_excl = a.max(b);

            (start < end_excl).then_some((start, end_excl))
        })
    }

    pub(super) fn build_from_vec(xs: Vec<(i16, i16)>) -> crate::I16COSet {
        let b = crate::I16COSetBuilder::new();

        for (start, end_excl) in xs {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
