// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::I16CO;
use proptest::prelude::*;

use crate::I16COSet;

#[inline]
pub(super) fn iv(start: i16, end_excl: i16) -> I16CO {
    I16CO::try_new(start, end_excl).unwrap()
}

#[inline]
pub(super) fn intervals(set: &I16COSet) -> &[I16CO] {
    set.intervals.as_ref()
}

#[inline]
pub(super) fn build<const N: usize>(pairs: [(i16, i16); N]) -> I16COSet {
    pairs
        .into_iter()
        .map(|(start, end)| iv(start, end))
        .collect()
}

/// Generates valid, non-empty intervals without enumerating the domain.
///
/// For code generation, replace `i16` and `I16CO` with the target primitive
/// and interval type.
pub(super) fn arb_iv() -> impl Strategy<Value = I16CO> {
    (any::<i16>(), any::<i16>()).prop_filter_map("interval endpoints must differ", |(a, b)| {
        let (start, end) = if a < b { (a, b) } else { (b, a) };
        I16CO::try_new(start, end)
    })
}
