// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod basic;
mod coverage;
mod predicate;
mod search;

mod test_support {
    use crate::{UsizeCOSetBuilder, usize::tests::test_support::iv};

    pub(super) fn build<const N: usize>(intervals: [(usize, usize); N]) -> crate::UsizeCOSet {
        let b = UsizeCOSetBuilder::new();

        for (start, end_excl) in intervals {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
