// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::U64CO;

/// Checks the canonical invariant used by binary-search queries.
///
/// `U64CO` itself already guarantees single-interval validity. This
/// function only checks the relationship between adjacent intervals.
#[inline]
pub(super) fn is_canonical(intervals: &[U64CO]) -> bool {
    intervals.windows(2).all(|w| w[0].end_excl() < w[1].start())
}

#[inline]
pub(super) fn normalize(mut intervals: Vec<U64CO>) -> Vec<U64CO> {
    intervals.sort_unstable();
    canonicalize_sorted(intervals)
}

#[inline]
pub(super) fn merge(left: Vec<U64CO>, right: Vec<U64CO>) -> Vec<U64CO> {
    if left.is_empty() {
        return right;
    }

    if right.is_empty() {
        return left;
    }

    canonicalize_sorted(merge_sorted(left, right))
}

pub(super) fn canonicalize_sorted<I>(intervals: I) -> Vec<U64CO>
where
    I: IntoIterator<Item = U64CO>,
{
    let mut iter = intervals.into_iter();

    let Some(mut cur) = iter.next() else {
        return Vec::new();
    };

    let mut out = Vec::new();

    for iv in iter {
        if cur.is_contiguous_with(iv) {
            cur = cur.convex_hull(iv);
        } else {
            out.push(cur);
            cur = iv;
        }
    }

    out.push(cur);
    out
}

pub(super) fn merge_sorted<I, J>(left: I, right: J) -> impl Iterator<Item = U64CO>
where
    I: IntoIterator<Item = U64CO>,
    J: IntoIterator<Item = U64CO>,
{
    struct Merge<I, J>
    where
        I: Iterator<Item = U64CO>,
        J: Iterator<Item = U64CO>,
    {
        left: std::iter::Peekable<I>,
        right: std::iter::Peekable<J>,
    }

    impl<I, J> Iterator for Merge<I, J>
    where
        I: Iterator<Item = U64CO>,
        J: Iterator<Item = U64CO>,
    {
        type Item = U64CO;

        #[inline]
        fn next(&mut self) -> Option<Self::Item> {
            match (self.left.peek(), self.right.peek()) {
                (Some(left), Some(right)) if left <= right => self.left.next(),
                (Some(_), Some(_)) => self.right.next(),
                (Some(_), None) => self.left.next(),
                (None, Some(_)) => self.right.next(),
                (None, None) => None,
            }
        }
    }

    Merge {
        left: left.into_iter().peekable(),
        right: right.into_iter().peekable(),
    }
}
