// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use super::*;

mod algebra_with_interval;
mod algebra_with_set;
