// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod builder;
mod set;

mod test_support {
    use int_interval::U64CO;

    use proptest::prelude::*;

    #[inline]
    pub(super) fn iv(start: u64, end_excl: u64) -> U64CO {
        U64CO::try_new(start, end_excl).unwrap()
    }

    pub(super) const MID_VALUE: u64 = u64::MAX / 2 + 1;

    pub(super) fn interval_pair() -> impl Strategy<Value = (u64, u64)> {
        (any::<u64>(), any::<u64>()).prop_filter_map("non-empty half-open interval", |(a, b)| {
            let start = a.min(b);
            let end_excl = a.max(b);

            (start < end_excl).then_some((start, end_excl))
        })
    }

    pub(super) fn build_from_vec(xs: Vec<(u64, u64)>) -> crate::U64COSet {
        let b = crate::U64COSetBuilder::new();

        for (start, end_excl) in xs {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
