// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::U64CO;
use proptest::prelude::*;

use crate::U64COSet;

#[inline]
pub(super) fn iv(start: u64, end_excl: u64) -> U64CO {
    U64CO::try_new(start, end_excl).unwrap()
}

#[inline]
pub(super) fn intervals(set: &U64COSet) -> &[U64CO] {
    set.intervals.as_ref()
}

#[inline]
pub(super) fn build<const N: usize>(pairs: [(u64, u64); N]) -> U64COSet {
    pairs
        .into_iter()
        .map(|(start, end)| iv(start, end))
        .collect()
}

/// Generates valid, non-empty intervals without enumerating the domain.
///
/// For code generation, replace `u64` and `U64CO` with the target primitive
/// and interval type.
pub(super) fn arb_iv() -> impl Strategy<Value = U64CO> {
    (any::<u64>(), any::<u64>()).prop_filter_map("interval endpoints must differ", |(a, b)| {
        let (start, end) = if a < b { (a, b) } else { (b, a) };
        U64CO::try_new(start, end)
    })
}
