// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod basic;
mod coverage;
mod predicate;
mod search;

mod test_support {
    use crate::{U128COSetBuilder, u128::tests::test_support::iv};

    pub(super) fn build<const N: usize>(intervals: [(u128, u128); N]) -> crate::U128COSet {
        let b = U128COSetBuilder::new();

        for (start, end_excl) in intervals {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
