// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use proptest::prelude::*;

use crate::{
    I32COSet,
    i32::test_support::{arb_iv, build, iv},
};

#[test]
fn intersection_with_empty_set_is_empty() {
    let empty = build([]);
    let set = build([(10, 20), (30, 40)]);

    assert!(empty.intersection_with_set(&set).is_empty());
    assert!(set.intersection_with_set(&empty).is_empty());
}

#[test]
fn intersection_of_disjoint_sets_is_empty() {
    let left = build([(10, 20), (30, 40)]);
    let right = build([(0, 10), (20, 30), (40, 50)]);

    assert!(left.intersection_with_set(&right).is_empty());
}

#[test]
fn intersection_returns_clipped_segments_from_both_sets() {
    let left = build([(0, 10), (20, 30), (40, 50)]);
    let right = build([(5, 25), (45, 60)]);

    assert_eq!(
        left.intersection_with_set(&right).as_slice(),
        &[iv(5, 10), iv(20, 25), iv(45, 50)]
    );
}

#[test]
fn intersection_handles_one_interval_overlapping_multiple_intervals() {
    let left = build([(5, 45)]);
    let right = build([(0, 10), (20, 30), (40, 50)]);

    assert_eq!(
        left.intersection_with_set(&right).as_slice(),
        &[iv(5, 10), iv(20, 30), iv(40, 45)]
    );
}

#[test]
fn intersection_preserves_fully_shared_intervals() {
    let left = build([(10, 20), (30, 40), (50, 60)]);
    let right = build([(10, 20), (30, 40), (50, 60)]);

    assert_eq!(left.intersection_with_set(&right), left);
}

#[test]
fn intersection_uses_canonical_source_intervals() {
    let left = build([(0, 5), (5, 10), (20, 25), (24, 30)]);
    let right = build([(8, 22)]);

    assert_eq!(left.as_slice(), &[iv(0, 10), iv(20, 30)]);
    assert_eq!(
        left.intersection_with_set(&right).as_slice(),
        &[iv(8, 10), iv(20, 22)]
    );
}

#[test]
fn intersection_handles_domain_edges() {
    let left = build([(i32::MIN, i32::MIN + 10), (i32::MAX - 10, i32::MAX)]);
    let right = build([(i32::MIN + 5, i32::MIN + 20), (i32::MAX - 5, i32::MAX)]);

    assert_eq!(
        left.intersection_with_set(&right).as_slice(),
        &[iv(i32::MIN + 5, i32::MIN + 10), iv(i32::MAX - 5, i32::MAX)]
    );
}

proptest! {
    #[test]
    fn prop_intersection_matches_pointwise_membership(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
        x in any::<i32>(),
    ) {
        let left: I32COSet = xs.into_iter().collect();
        let right: I32COSet = ys.into_iter().collect();
        let result = left.intersection_with_set(&right);

        prop_assert_eq!(
            result.contains_point(x),
            left.contains_point(x) && right.contains_point(x)
        );
    }

    #[test]
    fn prop_intersection_is_commutative(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: I32COSet = xs.into_iter().collect();
        let right: I32COSet = ys.into_iter().collect();

        prop_assert_eq!(
            left.intersection_with_set(&right),
            right.intersection_with_set(&left)
        );
    }

    #[test]
    fn prop_intersection_output_is_contained_by_both_inputs(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: I32COSet = xs.into_iter().collect();
        let right: I32COSet = ys.into_iter().collect();
        let result = left.intersection_with_set(&right);

        for interval in result.iter_intervals() {
            prop_assert!(left.contains_interval(interval));
            prop_assert!(right.contains_interval(interval));
        }
    }
}
