// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use proptest::prelude::*;

use crate::{
    I32COSet,
    i32::test_support::{arb_iv, build, iv},
};

#[test]
fn union_with_empty_set_returns_other_set() {
    let empty = build([]);
    let set = build([(10, 20), (30, 40)]);

    assert_eq!(empty.union_with_set(&set), set);
    assert_eq!(set.union_with_set(&empty), set);
}

#[test]
fn union_of_disjoint_sets_preserves_all_intervals_in_order() {
    let left = build([(10, 20), (50, 60)]);
    let right = build([(30, 40), (70, 80)]);

    assert_eq!(
        left.union_with_set(&right).as_slice(),
        &[iv(10, 20), iv(30, 40), iv(50, 60), iv(70, 80)]
    );
}

#[test]
fn union_merges_overlapping_intervals_from_both_sets() {
    let left = build([(0, 10), (20, 30), (50, 60)]);
    let right = build([(5, 25), (55, 70)]);

    assert_eq!(
        left.union_with_set(&right).as_slice(),
        &[iv(0, 30), iv(50, 70)]
    );
}

#[test]
fn union_merges_adjacent_intervals_across_sets() {
    let left = build([(0, 10), (30, 40)]);
    let right = build([(10, 20), (20, 30)]);

    assert_eq!(left.union_with_set(&right).as_slice(), &[iv(0, 40)]);
}

#[test]
fn union_bridges_multiple_intervals_from_both_sets() {
    let left = build([(0, 5), (20, 25), (40, 45)]);
    let right = build([(5, 20), (25, 40)]);

    assert_eq!(left.union_with_set(&right).as_slice(), &[iv(0, 45)]);
}

#[test]
fn union_returns_covering_set_when_other_is_fully_contained() {
    let left = build([(0, 50)]);
    let right = build([(10, 20), (30, 40)]);

    assert_eq!(left.union_with_set(&right), left);
    assert_eq!(right.union_with_set(&left), left);
}

#[test]
fn union_uses_canonical_source_intervals() {
    let left = build([(0, 5), (5, 10), (30, 35)]);
    let right = build([(8, 20), (20, 30)]);

    assert_eq!(left.as_slice(), &[iv(0, 10), iv(30, 35)]);
    assert_eq!(right.as_slice(), &[iv(8, 30)]);
    assert_eq!(left.union_with_set(&right).as_slice(), &[iv(0, 35)]);
}

#[test]
fn union_handles_domain_edges() {
    let left = build([(i32::MIN, i32::MIN + 10), (i32::MAX - 10, i32::MAX)]);
    let right = build([(i32::MIN + 10, i32::MAX - 10)]);

    assert_eq!(
        left.union_with_set(&right).as_slice(),
        &[iv(i32::MIN, i32::MAX)]
    );
}

proptest! {
    #[test]
    fn prop_union_matches_pointwise_membership(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
        x in any::<i32>(),
    ) {
        let left: I32COSet = xs.into_iter().collect();
        let right: I32COSet = ys.into_iter().collect();
        let result = left.union_with_set(&right);

        prop_assert_eq!(
            result.contains_point(x),
            left.contains_point(x) || right.contains_point(x)
        );
    }

    #[test]
    fn prop_union_is_commutative(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: I32COSet = xs.into_iter().collect();
        let right: I32COSet = ys.into_iter().collect();

        prop_assert_eq!(
            left.union_with_set(&right),
            right.union_with_set(&left)
        );
    }

    #[test]
    fn prop_union_contains_both_inputs(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: I32COSet = xs.into_iter().collect();
        let right: I32COSet = ys.into_iter().collect();
        let result = left.union_with_set(&right);

        for interval in left.iter_intervals() {
            prop_assert!(result.contains_interval(interval));
        }

        for interval in right.iter_intervals() {
            prop_assert!(result.contains_interval(interval));
        }
    }

    #[test]
    fn prop_union_matches_collect_reference_model(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: I32COSet = xs.into_iter().collect();
        let right: I32COSet = ys.into_iter().collect();

        let expected: I32COSet = left
            .iter_intervals()
            .chain(right.iter_intervals())
            .collect();

        prop_assert_eq!(left.union_with_set(&right), expected);
    }
}
