// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::I128CO;
use proptest::prelude::*;

use crate::I128COSet;

#[inline]
pub(super) fn iv(start: i128, end_excl: i128) -> I128CO {
    I128CO::try_new(start, end_excl).unwrap()
}

#[inline]
pub(super) fn intervals(set: &I128COSet) -> &[I128CO] {
    set.intervals.as_ref()
}

#[inline]
pub(super) fn build<const N: usize>(pairs: [(i128, i128); N]) -> I128COSet {
    pairs
        .into_iter()
        .map(|(start, end)| iv(start, end))
        .collect()
}

/// Generates valid, non-empty intervals without enumerating the domain.
///
/// For code generation, replace `i128` and `I128CO` with the target primitive
/// and interval type.
pub(super) fn arb_iv() -> impl Strategy<Value = I128CO> {
    (any::<i128>(), any::<i128>()).prop_filter_map("interval endpoints must differ", |(a, b)| {
        let (start, end) = if a < b { (a, b) } else { (b, a) };
        I128CO::try_new(start, end)
    })
}
