// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod builder;
mod set;

mod test_support {
    use int_interval::I128CO;

    use proptest::prelude::*;

    #[inline]
    pub(super) fn iv(start: i128, end_excl: i128) -> I128CO {
        I128CO::try_new(start, end_excl).unwrap()
    }

    pub(super) const MID_VALUE: i128 = 0;

    pub(super) fn interval_pair() -> impl Strategy<Value = (i128, i128)> {
        (any::<i128>(), any::<i128>()).prop_filter_map("non-empty half-open interval", |(a, b)| {
            let start = a.min(b);
            let end_excl = a.max(b);

            (start < end_excl).then_some((start, end_excl))
        })
    }

    pub(super) fn build_from_vec(xs: Vec<(i128, i128)>) -> crate::I128COSet {
        let b = crate::I128COSetBuilder::new();

        for (start, end_excl) in xs {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
