// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod basic;
mod coverage;
mod predicate;
mod search;

mod test_support {
    use crate::{U32COSetBuilder, u32::tests::test_support::iv};

    pub(super) fn build<const N: usize>(intervals: [(u32, u32); N]) -> crate::U32COSet {
        let b = U32COSetBuilder::new();

        for (start, end_excl) in intervals {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
