// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod basic;
mod coverage;
mod predicate;
mod search;

mod test_support {
    use crate::{U16COSetBuilder, u16::tests::test_support::iv};

    pub(super) fn build<const N: usize>(intervals: [(u16, u16); N]) -> crate::U16COSet {
        let b = U16COSetBuilder::new();

        for (start, end_excl) in intervals {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
