// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod builder;
mod set;

mod test_support {
    use int_interval::U32CO;

    use proptest::prelude::*;

    #[inline]
    pub(super) fn iv(start: u32, end_excl: u32) -> U32CO {
        U32CO::try_new(start, end_excl).unwrap()
    }

    pub(super) const MID_VALUE: u32 = u32::MAX / 2 + 1;

    pub(super) fn interval_pair() -> impl Strategy<Value = (u32, u32)> {
        (any::<u32>(), any::<u32>()).prop_filter_map("non-empty half-open interval", |(a, b)| {
            let start = a.min(b);
            let end_excl = a.max(b);

            (start < end_excl).then_some((start, end_excl))
        })
    }

    pub(super) fn build_from_vec(xs: Vec<(u32, u32)>) -> crate::U32COSet {
        let b = crate::U32COSetBuilder::new();

        for (start, end_excl) in xs {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
