// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::U32CO;
use proptest::prelude::*;

use crate::U32COSet;

#[inline]
pub(super) fn iv(start: u32, end_excl: u32) -> U32CO {
    U32CO::try_new(start, end_excl).unwrap()
}

#[inline]
pub(super) fn intervals(set: &U32COSet) -> &[U32CO] {
    set.intervals.as_ref()
}

#[inline]
pub(super) fn build<const N: usize>(pairs: [(u32, u32); N]) -> U32COSet {
    pairs
        .into_iter()
        .map(|(start, end)| iv(start, end))
        .collect()
}

/// Generates valid, non-empty intervals without enumerating the domain.
///
/// For code generation, replace `u32` and `U32CO` with the target primitive
/// and interval type.
pub(super) fn arb_iv() -> impl Strategy<Value = U32CO> {
    (any::<u32>(), any::<u32>()).prop_filter_map("interval endpoints must differ", |(a, b)| {
        let (start, end) = if a < b { (a, b) } else { (b, a) };
        U32CO::try_new(start, end)
    })
}
