// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::UsizeCO;
use proptest::prelude::*;

use crate::UsizeCOSet;

#[inline]
pub(super) fn iv(start: usize, end_excl: usize) -> UsizeCO {
    UsizeCO::try_new(start, end_excl).unwrap()
}

#[inline]
pub(super) fn intervals(set: &UsizeCOSet) -> &[UsizeCO] {
    set.intervals.as_ref()
}

#[inline]
pub(super) fn build<const N: usize>(pairs: [(usize, usize); N]) -> UsizeCOSet {
    pairs
        .into_iter()
        .map(|(start, end)| iv(start, end))
        .collect()
}

/// Generates valid, non-empty intervals without enumerating the domain.
///
/// For code generation, replace `usize` and `UsizeCO` with the target primitive
/// and interval type.
pub(super) fn arb_iv() -> impl Strategy<Value = UsizeCO> {
    (any::<usize>(), any::<usize>()).prop_filter_map("interval endpoints must differ", |(a, b)| {
        let (start, end) = if a < b { (a, b) } else { (b, a) };
        UsizeCO::try_new(start, end)
    })
}
