// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod builder;
mod set;

mod test_support {
    use int_interval::UsizeCO;

    use proptest::prelude::*;

    #[inline]
    pub(super) fn iv(start: usize, end_excl: usize) -> UsizeCO {
        UsizeCO::try_new(start, end_excl).unwrap()
    }

    pub(super) const MID_VALUE: usize = usize::MAX / 2 + 1;

    pub(super) fn interval_pair() -> impl Strategy<Value = (usize, usize)> {
        (any::<usize>(), any::<usize>()).prop_filter_map("non-empty half-open interval", |(a, b)| {
            let start = a.min(b);
            let end_excl = a.max(b);

            (start < end_excl).then_some((start, end_excl))
        })
    }

    pub(super) fn build_from_vec(xs: Vec<(usize, usize)>) -> crate::UsizeCOSet {
        let b = crate::UsizeCOSetBuilder::new();

        for (start, end_excl) in xs {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
