// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use proptest::prelude::*;

use crate::{
    IsizeCOSet,
    isize::test_support::{arb_iv, build, iv},
};

#[test]
fn symmetric_difference_with_empty_set_returns_query() {
    let set = build([]);
    let query = iv(10, 20);

    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[query]
    );
}

#[test]
fn symmetric_difference_with_disjoint_query_is_union() {
    let set = build([(10, 20), (30, 40)]);
    let query = iv(22, 25);

    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[iv(10, 20), iv(22, 25), iv(30, 40)]
    );
}

#[test]
fn symmetric_difference_merges_adjacent_disjoint_pieces_canonically() {
    let set = build([(10, 20), (30, 40)]);
    let query = iv(20, 30);

    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[iv(10, 40)]
    );
}

#[test]
fn symmetric_difference_removes_equal_interval() {
    let set = build([(10, 20)]);
    let query = iv(10, 20);

    assert!(set.symmetric_difference_with_interval(query).is_empty());
}

#[test]
fn symmetric_difference_splits_partially_overlapping_interval() {
    let set = build([(10, 20)]);
    let query = iv(15, 25);

    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[iv(10, 15), iv(20, 25)]
    );
}

#[test]
fn symmetric_difference_preserves_query_gaps_between_multiple_hits() {
    let set = build([(10, 20), (30, 40), (50, 60)]);
    let query = iv(15, 55);

    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[iv(10, 15), iv(20, 30), iv(40, 50), iv(55, 60)]
    );
}

#[test]
fn symmetric_difference_uses_canonical_source_intervals() {
    let set = build([(0, 5), (5, 10), (12, 20), (18, 30)]);
    let query = iv(8, 15);

    assert_eq!(set.as_slice(), &[iv(0, 10), iv(12, 30)]);
    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[iv(0, 8), iv(10, 12), iv(15, 30)]
    );
}

#[test]
fn symmetric_difference_handles_domain_edges() {
    let set = build([(isize::MIN, isize::MIN + 10), (isize::MAX - 10, isize::MAX)]);

    let query = iv(isize::MIN + 5, isize::MAX - 5);

    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[
            iv(isize::MIN, isize::MIN + 5),
            iv(isize::MIN + 10, isize::MAX - 10),
            iv(isize::MAX - 5, isize::MAX),
        ]
    );
}

#[test]
fn symmetric_difference_retains_query_tail_when_query_contains_source_interval() {
    let set = build([(0, 15)]);
    let query = iv(0, 127);

    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[iv(15, 127)]
    );
}

#[test]
fn symmetric_difference_retains_query_head_when_query_extends_left_of_source_interval() {
    let set = build([(20, 40)]);
    let query = iv(10, 30);

    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[iv(10, 20), iv(30, 40)]
    );
}

#[test]
fn symmetric_difference_merges_query_residual_adjacent_to_retained_suffix() {
    let set = build([(0, 5), (10, 15)]);
    let query = iv(2, 10);

    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[iv(0, 2), iv(5, 15)]
    );
}

#[test]
fn symmetric_difference_merges_query_residual_adjacent_to_retained_prefix() {
    let set = build([(0, 5), (10, 15)]);
    let query = iv(5, 12);

    assert_eq!(
        set.symmetric_difference_with_interval(query).as_slice(),
        &[iv(0, 10), iv(12, 15)]
    );
}

proptest! {
    #[test]
    fn prop_symmetric_difference_matches_exclusive_membership(
        xs in prop::collection::vec(arb_iv(), 0..64),
        query in arb_iv(),
        x in any::<isize>(),
    ) {
        let set: IsizeCOSet = xs.into_iter().collect();
        let result = set.symmetric_difference_with_interval(query);

        prop_assert_eq!(
            result.contains_point(x),
            set.contains_point(x) ^ query.contains(x)
        );
    }

    #[test]
    fn prop_symmetric_difference_with_disjoint_query_matches_union(
        xs in prop::collection::vec(arb_iv(), 0..64),
        query in arb_iv(),
    ) {
        let set: IsizeCOSet = xs.into_iter().collect();

        if !set.intersects_interval(query) {
            prop_assert_eq!(
                set.symmetric_difference_with_interval(query),
                set.union_with_interval(query)
            );
        }
    }

    #[test]
    fn prop_symmetric_difference_is_disjoint_from_intersection(
        xs in prop::collection::vec(arb_iv(), 0..64),
        query in arb_iv(),
    ) {
        let set: IsizeCOSet = xs.into_iter().collect();

        let symmetric = set.symmetric_difference_with_interval(query);
        let intersection = set.intersection_with_interval(query);

        for left in symmetric.iter_intervals() {
            for right in intersection.iter_intervals() {
                prop_assert!(!left.intersects(right));
            }
        }
    }
}
