pub const GENERATED_WARNING_BATCH: &str = "\
// -----------------------------------------------------------------------------\n\
// @generated by xtask/codegen (--batch --signed)\n\
// DO NOT EDIT MANUALLY.\n\
// Changes will be overwritten.\n\
// -----------------------------------------------------------------------------\n\n";

/// (primitive_type, interval_name, len_type, set_name)
pub const TYPES: &[(&str, &str, &str, &str)] = &[
    ("i16", "I16CO", "u16", "I16COBatchSet"),
    ("i32", "I32CO", "u32", "I32COBatchSet"),
    ("i64", "I64CO", "u64", "I64COBatchSet"),
    ("i128", "I128CO", "u128", "I128COBatchSet"),
    ("isize", "IsizeCO", "usize", "IsizeCOBatchSet"),
];

pub const TEMPLATE_TY: &str = "i8";
pub const TEMPLATE_INTERVAL_NAME: &str = "I8CO";
pub const TEMPLATE_LEN_TY: &str = "u8";
pub const TEMPLATE_SET_NAME: &str = "I8COBatchSet";

#[inline]
pub fn replace_batch(
    text: &str,
    dst_ty: &str,
    dst_interval_name: &str,
    dst_len_ty: &str,
    dst_set_name: &str,
) -> String {
    text.replace(TEMPLATE_SET_NAME, dst_set_name)
        .replace(TEMPLATE_INTERVAL_NAME, dst_interval_name)
        .replace(TEMPLATE_TY, dst_ty)
        .replace(TEMPLATE_LEN_TY, dst_len_ty)
}
