pub const GENERATED_WARNING_BATCH: &str = "\
// -----------------------------------------------------------------------------\n\
// @generated by xtask/codegen (--batch --unsigned)\n\
// DO NOT EDIT MANUALLY.\n\
// Changes will be overwritten.\n\
// -----------------------------------------------------------------------------\n\n";

/// (primitive_type, interval_name, set_name)
pub const TYPES: &[(&str, &str, &str)] = &[
    ("u16", "U16CO", "U16COBatchSet"),
    ("u32", "U32CO", "U32COBatchSet"),
    ("u64", "U64CO", "U64COBatchSet"),
    ("u128", "U128CO", "U128COBatchSet"),
    ("usize", "UsizeCO", "UsizeCOBatchSet"),
];

pub const TEMPLATE_TY: &str = "u8";
pub const TEMPLATE_INTERVAL_NAME: &str = "U8CO";
pub const TEMPLATE_SET_NAME: &str = "U8COBatchSet";

#[inline]
pub fn replace_batch(
    text: &str,
    dst_ty: &str,
    dst_interval_name: &str,
    dst_set_name: &str,
) -> String {
    text.replace(TEMPLATE_SET_NAME, dst_set_name)
        .replace(TEMPLATE_INTERVAL_NAME, dst_interval_name)
        .replace(TEMPLATE_TY, dst_ty)
}
