// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use proptest::prelude::*;

use crate::{
    IsizeCOSet,
    isize::test_support::{arb_iv, build, iv},
};

#[test]
fn returns_none_on_empty_set() {
    let set = build([]);

    assert_eq!(set.interval_containing_point(isize::MIN), None);
    assert_eq!(set.interval_containing_point(isize::MAX / 2), None);
    assert_eq!(set.interval_containing_point(isize::MAX), None);
}

#[test]
fn respects_half_open_bounds() {
    let set = build([(10, 20)]);

    assert_eq!(set.interval_containing_point(9), None);
    assert_eq!(set.interval_containing_point(10), Some(iv(10, 20)));
    assert_eq!(set.interval_containing_point(19), Some(iv(10, 20)));
    assert_eq!(set.interval_containing_point(20), None);
}

#[test]
fn returns_matching_interval_across_multiple_intervals() {
    let set = build([(10, 20), (30, 40), (50, 60)]);

    assert_eq!(set.interval_containing_point(10), Some(iv(10, 20)));
    assert_eq!(set.interval_containing_point(35), Some(iv(30, 40)));
    assert_eq!(set.interval_containing_point(59), Some(iv(50, 60)));

    assert_eq!(set.interval_containing_point(0), None);
    assert_eq!(set.interval_containing_point(20), None);
    assert_eq!(set.interval_containing_point(45), None);
    assert_eq!(set.interval_containing_point(isize::MAX), None);
}

#[test]
fn returns_merged_interval_after_canonicalization() {
    let set = build([(0, 5), (5, 10), (12, 20), (18, 30)]);

    assert_eq!(set.as_slice(), &[iv(0, 10), iv(12, 30)]);

    assert_eq!(set.interval_containing_point(0), Some(iv(0, 10)));
    assert_eq!(set.interval_containing_point(9), Some(iv(0, 10)));
    assert_eq!(set.interval_containing_point(10), None);
    assert_eq!(set.interval_containing_point(11), None);
    assert_eq!(set.interval_containing_point(12), Some(iv(12, 30)));
    assert_eq!(set.interval_containing_point(29), Some(iv(12, 30)));
    assert_eq!(set.interval_containing_point(30), None);
}

#[test]
fn handles_domain_edges() {
    let set = build([(isize::MIN, isize::MIN + 1), (isize::MAX - 1, isize::MAX)]);

    assert_eq!(
        set.interval_containing_point(isize::MIN),
        Some(iv(isize::MIN, isize::MIN + 1))
    );
    assert_eq!(set.interval_containing_point(isize::MIN + 1), None);

    assert_eq!(
        set.interval_containing_point(isize::MAX - 1),
        Some(iv(isize::MAX - 1, isize::MAX))
    );
    assert_eq!(set.interval_containing_point(isize::MAX), None);
}

#[test]
fn representative_points_match_contains_point_predicate() {
    let set = build([(10, 20), (30, 40), (50, 60)]);

    for x in [isize::MIN, 9, 10, 19, 20, 30, 39, 40, 55, 60, isize::MAX] {
        assert_eq!(
            set.interval_containing_point(x).is_some(),
            set.contains_point(x),
            "point = {x}"
        );
    }
}

proptest! {
    #[test]
    fn prop_interval_containing_point_matches_slice_find(
        xs in prop::collection::vec(arb_iv(), 0..64),
        x in any::<isize>(),
    ) {
        let set: IsizeCOSet = xs.into_iter().collect();

        let got = set.interval_containing_point(x);
        let expected = set
            .as_slice()
            .iter()
            .copied()
            .find(|iv| iv.contains(x));

        prop_assert_eq!(got, expected);
    }

    #[test]
    fn prop_interval_containing_point_matches_contains_point(
        xs in prop::collection::vec(arb_iv(), 0..64),
        x in any::<isize>(),
    ) {
        let set: IsizeCOSet = xs.into_iter().collect();

        prop_assert_eq!(
            set.interval_containing_point(x).is_some(),
            set.contains_point(x)
        );
    }
}
