// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use proptest::prelude::*;

use crate::{
    UsizeCOSet,
    usize::test_support::{arb_iv, build, iv},
};

#[test]
fn symmetric_difference_with_empty_set_returns_other_set() {
    let empty = build([]);
    let set = build([(10, 20), (30, 40)]);

    assert_eq!(empty.symmetric_difference_with_set(&set), set);
    assert_eq!(set.symmetric_difference_with_set(&empty), set);
}

#[test]
fn symmetric_difference_of_identical_sets_is_empty() {
    let set = build([(10, 20), (30, 40)]);

    assert!(set.symmetric_difference_with_set(&set).is_empty());
}

#[test]
fn symmetric_difference_removes_overlapping_segments() {
    let left = build([(0, 10), (20, 30)]);
    let right = build([(5, 15), (25, 35)]);

    assert_eq!(
        left.symmetric_difference_with_set(&right).as_slice(),
        &[iv(0, 5), iv(10, 15), iv(20, 25), iv(30, 35)]
    );
}

#[test]
fn symmetric_difference_merges_adjacent_disjoint_coverage() {
    let left = build([(0, 10), (30, 40)]);
    let right = build([(10, 30)]);

    assert_eq!(
        left.symmetric_difference_with_set(&right).as_slice(),
        &[iv(0, 40)]
    );
}

#[test]
fn symmetric_difference_retains_gaps_between_removed_segments() {
    let left = build([(0, 50)]);
    let right = build([(10, 20), (30, 40)]);

    assert_eq!(
        left.symmetric_difference_with_set(&right).as_slice(),
        &[iv(0, 10), iv(20, 30), iv(40, 50)]
    );
}

#[test]
fn symmetric_difference_handles_crossing_long_intervals() {
    let left = build([(0, 10), (20, 30), (40, 50)]);
    let right = build([(5, 45)]);

    assert_eq!(
        left.symmetric_difference_with_set(&right).as_slice(),
        &[iv(0, 5), iv(10, 20), iv(30, 40), iv(45, 50)]
    );
}

#[test]
fn symmetric_difference_handles_domain_edges() {
    let left = build([(usize::MIN, usize::MIN + 10), (usize::MAX - 10, usize::MAX)]);
    let right = build([(usize::MIN + 5, usize::MAX - 5)]);

    assert_eq!(
        left.symmetric_difference_with_set(&right).as_slice(),
        &[
            iv(usize::MIN, usize::MIN + 5),
            iv(usize::MIN + 10, usize::MAX - 10),
            iv(usize::MAX - 5, usize::MAX),
        ]
    );
}

proptest! {
    #[test]
    fn prop_symmetric_difference_matches_pointwise_membership(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
        x in any::<usize>(),
    ) {
        let left: UsizeCOSet = xs.into_iter().collect();
        let right: UsizeCOSet = ys.into_iter().collect();
        let result = left.symmetric_difference_with_set(&right);

        prop_assert_eq!(
            result.contains_point(x),
            left.contains_point(x) ^ right.contains_point(x)
        );
    }

    #[test]
    fn prop_symmetric_difference_is_commutative(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: UsizeCOSet = xs.into_iter().collect();
        let right: UsizeCOSet = ys.into_iter().collect();

        prop_assert_eq!(
            left.symmetric_difference_with_set(&right),
            right.symmetric_difference_with_set(&left)
        );
    }

    #[test]
    fn prop_symmetric_difference_matches_difference_union_reference_model(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: UsizeCOSet = xs.into_iter().collect();
        let right: UsizeCOSet = ys.into_iter().collect();

        let expected = left
            .difference_with_set(&right)
            .union_with_set(&right.difference_with_set(&left));

        prop_assert_eq!(left.symmetric_difference_with_set(&right), expected);
    }

    #[test]
    fn prop_symmetric_difference_is_disjoint_from_intersection(
        xs in prop::collection::vec(arb_iv(), 0..64),
        ys in prop::collection::vec(arb_iv(), 0..64),
    ) {
        let left: UsizeCOSet = xs.into_iter().collect();
        let right: UsizeCOSet = ys.into_iter().collect();

        let symmetric = left.symmetric_difference_with_set(&right);
        let intersection = left.intersection_with_set(&right);

        prop_assert!(
            symmetric.intersection_with_set(&intersection).is_empty()
        );
    }
}
