// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod basic;
mod coverage;
mod predicate;
mod search;

mod test_support {
    use crate::{U64COSetBuilder, u64::tests::test_support::iv};

    pub(super) fn build<const N: usize>(intervals: [(u64, u64); N]) -> crate::U64COSet {
        let b = U64COSetBuilder::new();

        for (start, end_excl) in intervals {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
