// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use crate::u16::funcs_for_canonicalization::{canonicalize_sorted, merge_sorted};

use super::*;

impl U16COSet {
    /// Returns the intersection of this set and `other`.
    ///
    /// Both sets are canonical, so their sorted interval slices can be
    /// intersected with a two-pointer scan.
    ///
    /// Example:
    ///
    /// ```text
    /// self:  [0, 10), [20, 30), [40, 50)
    /// other: [5, 25), [45, 60)
    /// out:   [5, 10), [20, 25), [45, 50)
    /// ```
    ///
    /// Complexity: `O(n + m)`, where `n` and `m` are the canonical
    /// interval counts of the two input sets.
    #[inline]
    pub fn intersection_with_set(&self, other: &Self) -> Self {
        if self.is_empty() {
            return self.clone();
        }

        if other.is_empty() {
            return other.clone();
        }

        let mut left = 0;
        let mut right = 0;
        let mut intervals = Vec::with_capacity(self.intervals.len().min(other.intervals.len()));

        while left < self.intervals.len() && right < other.intervals.len() {
            let a = self.intervals[left];
            let b = other.intervals[right];

            if let Some(intersection) = a.intersection(b) {
                intervals.push(intersection);
            }

            match a.end_excl().cmp(&b.end_excl()) {
                std::cmp::Ordering::Less => left += 1,
                std::cmp::Ordering::Greater => right += 1,
                std::cmp::Ordering::Equal => {
                    left += 1;
                    right += 1;
                }
            }
        }

        // SAFETY:
        // - Both source slices are canonical and sorted.
        // - Each emitted interval is an intersection of one source interval
        //   from each set.
        // - Advancing the interval with the smaller end preserves output order.
        // - Distinct emitted intervals cannot overlap or become adjacent,
        //   because adjacency has already been merged in both source sets.
        unsafe { Self::new_unchecked(intervals) }
    }

    #[inline]
    pub fn union_with_set(&self, other: &Self) -> Self {
        if self.is_empty() {
            return other.clone();
        }

        if other.is_empty() {
            return self.clone();
        }

        let intervals = canonicalize_sorted(merge_sorted(
            self.intervals.iter().copied(),
            other.intervals.iter().copied(),
        ));

        // SAFETY:
        // - Both source sets yield sorted canonical interval sequences.
        // - `merge_sorted` preserves ascending order.
        // - `canonicalize_sorted` merges every overlap or adjacency.
        // - Therefore the resulting interval slice is canonical.
        unsafe { Self::new_unchecked(intervals) }
    }

    /// Returns the difference of this set and `other`.
    ///
    /// The returned set contains every point covered by `self` but not by
    /// `other`.
    ///
    /// Both source sets are canonical, so intervals from `other` are scanned
    /// monotonically while residual segments from `self` are emitted.
    ///
    /// Example:
    ///
    /// ```text
    /// self:  [0, 10), [20, 30), [40, 50)
    /// other: [5, 25), [45, 60)
    /// out:   [0, 5), [25, 30), [40, 45)
    /// ```
    ///
    /// Complexity: `O(n + m)`, where `n` and `m` are the canonical
    /// interval counts of the two input sets.
    #[inline]
    pub fn difference_with_set(&self, other: &Self) -> Self {
        if self.is_empty() || other.is_empty() {
            return self.clone();
        }

        // Index of the earliest removal interval that may still affect the
        // current or a later source interval.
        let mut remove_start_idx = 0;
        let mut intervals = Vec::with_capacity(self.intervals.len());

        for source in self.intervals.iter().copied() {
            // Discard removal intervals entirely to the left of `source`.
            // They cannot intersect this source or any later source.
            while remove_start_idx < other.intervals.len()
                && other.intervals[remove_start_idx].end_excl() <= source.start()
            {
                remove_start_idx += 1;
            }

            // Left boundary of the not-yet-processed portion of `source`.
            let mut cursor = source.start();

            // Temporary removal scan for this source interval.
            let mut scan = remove_start_idx;

            while scan < other.intervals.len() {
                let removed = other.intervals[scan];

                // No later removal interval can intersect this source.
                if removed.start() >= source.end_excl() {
                    break;
                }

                // Retain the uncovered segment preceding `removed`, if non-empty.
                if let Some(residual) = U16CO::try_new(cursor, removed.start()) {
                    intervals.push(residual);
                }

                // Advance beyond the points covered by `removed`.
                cursor = cursor.max(removed.end_excl());

                // This source has been removed through its right boundary.
                // Keep `scan` unchanged because this removal interval may continue
                // into later source intervals.
                if cursor >= source.end_excl() {
                    break;
                }

                // `removed` ended within this source; inspect the next removal.
                scan += 1;
            }

            // Retain the trailing uncovered segment, if any.
            if let Some(residual) = U16CO::try_new(cursor, source.end_excl()) {
                intervals.push(residual);
            }

            // The next source can resume from this position. The current removal
            // interval may still overlap it, so `scan` must not be incremented
            // unconditionally.
            remove_start_idx = scan;
        }
        // SAFETY:
        // - Source intervals are visited in canonical order.
        // - Each emitted interval is a residual segment of one source interval.
        // - Residual segments from the same source are separated by removed
        //   coverage; distinct source intervals were already strictly separated.
        unsafe { Self::new_unchecked(intervals) }
    }

    /// Returns the symmetric difference of this set and `other`.
    ///
    /// The returned set contains every point covered by exactly one of the two
    /// input sets.
    ///
    /// Both source sets are canonical. Their ordered boundary events are scanned
    /// together while tracking whether each side currently covers the sweep
    /// position.
    ///
    /// Example:
    ///
    /// ```text
    /// self:  [0, 10), [20, 30)
    /// other: [5, 15), [25, 35)
    /// out:   [0, 5), [10, 15), [20, 25), [30, 35)
    /// ```
    ///
    /// Complexity: `O(n + m)`, where `n` and `m` are the canonical interval
    /// counts of the two input sets.
    #[inline]
    pub fn symmetric_difference_with_set(&self, other: &Self) -> Self {
        if self.is_empty() {
            return other.clone();
        }

        if other.is_empty() {
            return self.clone();
        }

        // Each stream is already sorted because each source set is canonical:
        //
        // [start_0, end_0), [start_1, end_1), ...
        //  -> start_0, end_0, start_1, end_1, ...
        let mut left_events = self
            .intervals
            .iter()
            .copied()
            .flat_map(|iv| [(iv.start(), true), (iv.end_excl(), false)])
            .peekable();

        let mut right_events = other
            .intervals
            .iter()
            .copied()
            .flat_map(|iv| [(iv.start(), true), (iv.end_excl(), false)])
            .peekable();

        let mut left_covered = false;
        let mut right_covered = false;
        let mut opened_at = None;

        let mut intervals = Vec::with_capacity(self.intervals.len() + other.intervals.len());

        while left_events.peek().is_some() || right_events.peek().is_some() {
            // Next boundary coordinate from either source.
            let x = match (left_events.peek(), right_events.peek()) {
                (Some((left_x, _)), Some((right_x, _))) => (*left_x).min(*right_x),
                (Some((left_x, _)), None) => *left_x,
                (None, Some((right_x, _))) => *right_x,
                (None, None) => unreachable!(),
            };

            let covered_and_only_one_side_covered_before = left_covered ^ right_covered;

            // Process every boundary at `x` before evaluating the new XOR state.
            // This preserves canonical output when one set ends exactly where the
            // other begins.
            while left_events.peek().is_some_and(|(event_x, _)| *event_x == x) {
                let (_, starts) = left_events.next().unwrap();
                left_covered = starts;
            }

            while right_events
                .peek()
                .is_some_and(|(event_x, _)| *event_x == x)
            {
                let (_, starts) = right_events.next().unwrap();
                right_covered = starts;
            }

            let covered_and_only_one_side_covered_after = left_covered ^ right_covered;

            match (
                covered_and_only_one_side_covered_before,
                covered_and_only_one_side_covered_after,
            ) {
                // Enter a region covered by exactly one input set.
                (false, true) => opened_at = Some(x),

                // Leave such a region and emit its canonical interval.
                (true, false) => {
                    let start = opened_at
                        .take()
                        .expect("symmetric difference region must have a start");

                    let interval = U16CO::try_new(start, x)
                        .expect("symmetric difference region must be non-empty");

                    intervals.push(interval);
                }

                // Coverage parity did not change:
                // - false -> false: remain outside the result;
                // - true -> true: remain inside one continuous result interval.
                _ => {}
            }
        }

        debug_assert!(opened_at.is_none());

        // SAFETY:
        // - Boundary coordinates are visited in ascending order.
        // - An interval is emitted exactly when XOR coverage changes from true
        //   to false.
        // - Equal-coordinate boundary events are processed together, so touching
        //   XOR-covered regions are emitted as one interval rather than adjacent
        //   intervals.
        // - Therefore the resulting slice is sorted, non-overlapping, and
        //   non-adjacent.
        unsafe { Self::new_unchecked(intervals) }
    }
}

#[cfg(test)]
mod tests_for_difference;
#[cfg(test)]
mod tests_for_intersection;
#[cfg(test)]
mod tests_for_symmetric_difference;
#[cfg(test)]
mod tests_for_union;
