// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod basic;
mod coverage;
mod predicate;
mod search;

mod test_support {
    use crate::{I32COSetBuilder, i32::tests::test_support::iv};

    pub(super) fn build<const N: usize>(intervals: [(i32, i32); N]) -> crate::I32COSet {
        let b = I32COSetBuilder::new();

        for (start, end_excl) in intervals {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
