// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use crate::usize::tests::{
    set::test_support::build,
    test_support::{build_from_vec, interval_pair, iv},
};

#[test]
fn coverage_empty_set_has_zero_covered_len() {
    let set = build([]);

    let query = iv(10, 20);

    assert_eq!(set.covered_len(query), 0);
    assert_eq!(set.uncovered_len(query), query.len());
    assert_eq!(set.coverage_ratio(query), 0.0);
}

#[test]
fn coverage_full_cover_has_full_covered_len() {
    let set = build([(10, 20)]);

    let query = iv(10, 20);

    assert_eq!(set.covered_len(query), 10);
    assert_eq!(set.uncovered_len(query), 0);
    assert_eq!(set.coverage_ratio(query), 1.0);
}

#[test]
fn coverage_partial_cover_inside_single_interval() {
    let set = build([(10, 20)]);

    let query = iv(15, 25);

    assert_eq!(set.covered_len(query), 5);
    assert_eq!(set.uncovered_len(query), 5);
    assert_eq!(set.coverage_ratio(query), 0.5);
}

#[test]
fn coverage_gap_only_query_has_zero_covered_len() {
    let set = build([(10, 20), (30, 40)]);

    let query = iv(20, 30);

    assert_eq!(set.covered_len(query), 0);
    assert_eq!(set.uncovered_len(query), 10);
    assert_eq!(set.coverage_ratio(query), 0.0);
}

#[test]
fn coverage_across_multiple_intervals() {
    let set = build([(10, 20), (30, 40), (50, 60)]);

    let query = iv(15, 55);

    assert_eq!(
        set.intersections(query).collect::<Vec<_>>(),
        vec![iv(15, 20), iv(30, 40), iv(50, 55),]
    );

    assert_eq!(set.covered_len(query), 20);
    assert_eq!(set.uncovered_len(query), 20);
    assert_eq!(set.coverage_ratio(query), 0.5);
}

#[test]
fn coverage_uses_canonical_merged_intervals() {
    let set = build([(0, 5), (5, 10), (12, 20), (18, 30)]);

    assert_eq!(set.as_slice(), &[iv(0, 10), iv(12, 30)]);

    let query = iv(5, 15);

    assert_eq!(
        set.intersections(query).collect::<Vec<_>>(),
        vec![iv(5, 10), iv(12, 15),]
    );

    assert_eq!(set.covered_len(query), 8);
    assert_eq!(set.uncovered_len(query), 2);
    assert_eq!(set.coverage_ratio(query), 0.8);
}

#[test]
fn coverage_query_containing_all_intervals() {
    let set = build([(10, 20), (30, 40)]);

    let query = iv(0, 50);

    assert_eq!(set.covered_len(query), 20);
    assert_eq!(set.uncovered_len(query), 30);
    assert_eq!(set.coverage_ratio(query), 0.4);
}

#[test]
fn coverage_handles_domain_edges() {
    let set = build([(usize::MIN, usize::MIN + 1), (usize::MAX - 1, usize::MAX)]);

    let left_query = iv(usize::MIN, usize::MIN + 2);
    let right_query = iv(usize::MAX - 2, usize::MAX);

    assert_eq!(set.covered_len(left_query), 1);
    assert_eq!(set.uncovered_len(left_query), 1);
    assert_eq!(set.coverage_ratio(left_query), 0.5);

    assert_eq!(set.covered_len(right_query), 1);
    assert_eq!(set.uncovered_len(right_query), 1);
    assert_eq!(set.coverage_ratio(right_query), 0.5);
}

#[test]
fn coverage_lengths_add_up_to_query_len() {
    let set = build([(10, 20), (30, 40), (50, 60)]);

    for query in [
        iv(0, 10),
        iv(9, 11),
        iv(15, 35),
        iv(20, 30),
        iv(35, 55),
        iv(55, 61),
        iv(usize::MIN, usize::MIN + 1),
        iv(usize::MAX - 1, usize::MAX),
    ] {
        assert_eq!(
            set.covered_len(query) + set.uncovered_len(query),
            query.len(),
            "query = {query:?}"
        );
    }
}

#[test]
fn coverage_ratio_matches_covered_len_over_query_len() {
    let set = build([(10, 20), (30, 40), (50, 60)]);

    for query in [
        iv(0, 10),
        iv(9, 11),
        iv(15, 35),
        iv(20, 30),
        iv(35, 55),
        iv(55, 61),
        iv(usize::MIN, usize::MIN + 1),
        iv(usize::MAX - 1, usize::MAX),
    ] {
        let expected = set.covered_len(query) as f32 / query.len() as f32;

        assert_eq!(set.coverage_ratio(query), expected, "query = {query:?}");
    }
}

use proptest::prelude::*;

proptest! {
    #[test]
    fn prop_coverage_lengths_partition_query(
        xs in prop::collection::vec(interval_pair(), 0..64),
        query in interval_pair(),
    ) {
        let set = build_from_vec(xs);
        let query = iv(query.0, query.1);

        prop_assert_eq!(
            set.covered_len(query) + set.uncovered_len(query),
            query.len()
        );
    }

    #[test]
    fn prop_covered_len_matches_intersection_predicate(
        xs in prop::collection::vec(interval_pair(), 0..64),
        query in interval_pair(),
    ) {
        let set = build_from_vec(xs);
        let query = iv(query.0, query.1);

        prop_assert_eq!(
            set.covered_len(query) > 0,
            set.intersects_interval(query)
        );
    }
}
