// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use crate::u128::test_support::{intervals, iv};

use super::*;

#[test]
fn from_par_iter_empty() {
    let set: U128COSet = Vec::<U128CO>::new().into_par_iter().collect();

    assert!(intervals(&set).is_empty());
}

#[test]
fn from_par_iter_sorts_and_merges_overlap_adjacency_and_duplicates() {
    let set: U128COSet = [
        iv(12, 14),
        iv(0, 3),
        iv(2, 6), // overlaps [0, 3)
        iv(8, 10),
        iv(6, 8),   // connects [0, 6) with [8, 10)
        iv(12, 14), // duplicate
        iv(10, 11), // remains separated from [12, 14)
    ]
    .into_par_iter()
    .collect();

    assert_eq!(intervals(&set), &[iv(0, 11), iv(12, 14)]);
}

#[test]
fn from_par_iter_merges_many_reduced_runs() {
    let mut input = Vec::with_capacity(BATCH_SIZE * 8 + 4);

    input.extend(std::iter::repeat_n(iv(0, 2), BATCH_SIZE * 2));
    input.extend(std::iter::repeat_n(iv(6, 8), BATCH_SIZE * 2));
    input.extend(std::iter::repeat_n(iv(2, 4), BATCH_SIZE * 2));
    input.extend(std::iter::repeat_n(iv(4, 6), BATCH_SIZE * 2));
    input.extend([iv(20, 22), iv(21, 24), iv(30, 31), iv(30, 31)]);

    let set: U128COSet = input.into_par_iter().collect();

    assert_eq!(intervals(&set), &[iv(0, 8), iv(20, 24), iv(30, 31)]);
    assert!(is_canonical(intervals(&set)));
}

#[test]
fn from_par_iter_matches_whole_input_normalization() {
    let input = [
        iv(30, 35),
        iv(1, 4),
        iv(7, 10),
        iv(3, 8),
        iv(50, 51),
        iv(49, 50),
        iv(20, 22),
        iv(21, 25),
        iv(30, 35),
    ];

    let expected = normalize(input.to_vec());
    let set: U128COSet = input.into_par_iter().collect();

    assert_eq!(intervals(&set), expected.as_slice());
    assert!(is_canonical(intervals(&set)));
}

#[test]
fn from_par_iter_matches_from_iter_for_large_input() {
    let input: Vec<U128CO> = (0..BATCH_SIZE * 16)
        .map(|i| match i % 8 {
            0 => iv(40, 45),
            1 => iv(0, 2),
            2 => iv(10, 12),
            3 => iv(2, 6),
            4 => iv(11, 15),
            5 => iv(30, 31),
            6 => iv(31, 34),
            _ => iv(60, 61),
        })
        .collect();

    let sequential: U128COSet = input.iter().copied().collect();
    let parallel: U128COSet = input.into_par_iter().collect();

    assert_eq!(parallel, sequential);
    assert!(is_canonical(intervals(&parallel)));
}
