// -----------------------------------------------------------------------------
// @generated by xtask/codegen (--batch)
// DO NOT EDIT MANUALLY.
// Changes will be overwritten.
// -----------------------------------------------------------------------------

mod u8;
mod u16;
mod u32;
mod u64;
mod u128;
mod usize;
mod i8;
mod i16;
mod i32;
mod i64;
mod i128;
mod isize;

pub use u8::U8COBatchSet;
pub use u16::U16COBatchSet;
pub use u32::U32COBatchSet;
pub use u64::U64COBatchSet;
pub use u128::U128COBatchSet;
pub use usize::UsizeCOBatchSet;
pub use i8::I8COBatchSet;
pub use i16::I16COBatchSet;
pub use i32::I32COBatchSet;
pub use i64::I64COBatchSet;
pub use i128::I128COBatchSet;
pub use isize::IsizeCOBatchSet;
