// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

#[cfg(test)]
mod test_support;

use std::sync::Arc;

use int_interval::I8CO;

/// Immutable canonical interval set.
///
/// Internally this is an `Arc<[I8CO]>`, so cloning a `I8COSet` is cheap.
///
/// Canonical invariant:
///
/// ```text
/// for every adjacent pair a, b:
///     a.end_excl() < b.start()
/// ```
///
/// The strict `<` means both overlap and adjacency have already been merged.
#[repr(transparent)]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct I8COSet {
    intervals: Arc<[I8CO]>,
}

mod impls_for_accessors;
mod impls_for_algebra;
mod impls_for_construction;
mod impls_for_find_out_coverage;
mod impls_for_predicates;
mod impls_for_searching;

mod funcs_for_canonicalization;
