mod u8;

pub use u8::U8COSet;

// codegen:integer:start
// This block is generated by `cargo run -p codegen`.
// Do not edit manually.
mod i8;
mod u16;
mod i16;
mod u32;
mod i32;
mod u64;
mod i64;
mod u128;
mod i128;
mod usize;
mod isize;

pub use i8::I8COSet;
pub use u16::U16COSet;
pub use i16::I16COSet;
pub use u32::U32COSet;
pub use i32::I32COSet;
pub use u64::U64COSet;
pub use i64::I64COSet;
pub use u128::U128COSet;
pub use i128::I128COSet;
pub use usize::UsizeCOSet;
pub use isize::IsizeCOSet;
// codegen:integer:end
