mod u8;

pub use u8::U8COSet;

mod i8;

pub use i8::builder::I8COSetBuilder;
pub use i8::set::I8COSet;

// codegen:unsigned:start
// This block is generated by `cargo run -p codegen -- --unsigned`.
// Do not edit manually.
mod u128;
mod u16;
mod u32;
mod u64;
mod usize;

pub use u16::builder::U16COSetBuilder;
pub use u16::set::U16COSet;
pub use u32::builder::U32COSetBuilder;
pub use u32::set::U32COSet;
pub use u64::builder::U64COSetBuilder;
pub use u64::set::U64COSet;
pub use u128::builder::U128COSetBuilder;
pub use u128::set::U128COSet;
pub use usize::builder::UsizeCOSetBuilder;
pub use usize::set::UsizeCOSet;
// codegen:unsigned:end
// codegen:signed:start
// This block is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
mod i128;
mod i16;
mod i32;
mod i64;
mod isize;

pub use i16::builder::I16COSetBuilder;
pub use i16::set::I16COSet;
pub use i32::builder::I32COSetBuilder;
pub use i32::set::I32COSet;
pub use i64::builder::I64COSetBuilder;
pub use i64::set::I64COSet;
pub use i128::builder::I128COSetBuilder;
pub use i128::set::I128COSet;
pub use isize::builder::IsizeCOSetBuilder;
pub use isize::set::IsizeCOSet;
// codegen:signed:end
