// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen -- --signed`.
// Do not edit manually.
// -----------------------------------------------------------------------------

mod builder;
mod set;

mod test_support {
    use int_interval::I32CO;

    use proptest::prelude::*;

    #[inline]
    pub(super) fn iv(start: i32, end_excl: i32) -> I32CO {
        I32CO::try_new(start, end_excl).unwrap()
    }

    pub(super) const MID_VALUE: i32 = 0;

    pub(super) fn interval_pair() -> impl Strategy<Value = (i32, i32)> {
        (any::<i32>(), any::<i32>()).prop_filter_map("non-empty half-open interval", |(a, b)| {
            let start = a.min(b);
            let end_excl = a.max(b);

            (start < end_excl).then_some((start, end_excl))
        })
    }

    pub(super) fn build_from_vec(xs: Vec<(i32, i32)>) -> crate::I32COSet {
        let b = crate::I32COSetBuilder::new();

        for (start, end_excl) in xs {
            b.insert(iv(start, end_excl));
        }

        b.seal()
    }
}
