// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use int_interval::I32CO;
use proptest::prelude::*;

use crate::I32COSet;

#[inline]
pub(super) fn iv(start: i32, end_excl: i32) -> I32CO {
    I32CO::try_new(start, end_excl).unwrap()
}

#[inline]
pub(super) fn intervals(set: &I32COSet) -> &[I32CO] {
    set.intervals.as_ref()
}

#[inline]
pub(super) fn build<const N: usize>(pairs: [(i32, i32); N]) -> I32COSet {
    pairs
        .into_iter()
        .map(|(start, end)| iv(start, end))
        .collect()
}

/// Generates valid, non-empty intervals without enumerating the domain.
///
/// For code generation, replace `i32` and `I32CO` with the target primitive
/// and interval type.
pub(super) fn arb_iv() -> impl Strategy<Value = I32CO> {
    (any::<i32>(), any::<i32>()).prop_filter_map("interval endpoints must differ", |(a, b)| {
        let (start, end) = if a < b { (a, b) } else { (b, a) };
        I32CO::try_new(start, end)
    })
}
