// -----------------------------------------------------------------------------
// This file is generated by `cargo run -p codegen`.
// Do not edit manually.
// -----------------------------------------------------------------------------

use proptest::prelude::*;

use crate::{
    I128COSet,
    i128::test_support::{arb_iv, build, iv},
};

#[test]
fn returns_empty_on_empty_set() {
    let set = build([]);
    let query = iv(0, 1);

    assert_eq!(
        set.intervals_intersecting(query).collect::<Vec<_>>(),
        vec![]
    );
}

#[test]
fn respects_half_open_bounds() {
    let set = build([(10, 20), (30, 40)]);

    assert_eq!(
        set.intervals_intersecting(iv(0, 10)).collect::<Vec<_>>(),
        vec![]
    );
    assert_eq!(
        set.intervals_intersecting(iv(20, 30)).collect::<Vec<_>>(),
        vec![]
    );
    assert_eq!(
        set.intervals_intersecting(iv(40, 50)).collect::<Vec<_>>(),
        vec![]
    );

    assert_eq!(
        set.intervals_intersecting(iv(9, 11)).collect::<Vec<_>>(),
        vec![iv(10, 20)]
    );
    assert_eq!(
        set.intervals_intersecting(iv(19, 21)).collect::<Vec<_>>(),
        vec![iv(10, 20)]
    );
}

#[test]
fn returns_original_canonical_intervals() {
    let set = build([(10, 20), (30, 40), (50, 60)]);
    let query = iv(15, 55);

    assert_eq!(
        set.intervals_intersecting(query).collect::<Vec<_>>(),
        vec![iv(10, 20), iv(30, 40), iv(50, 60)]
    );
}

#[test]
fn uses_canonical_merged_intervals() {
    let set = build([(0, 5), (5, 10), (12, 20), (18, 30)]);
    let query = iv(9, 13);

    assert_eq!(set.as_slice(), &[iv(0, 10), iv(12, 30)]);
    assert_eq!(
        set.intervals_intersecting(query).collect::<Vec<_>>(),
        vec![iv(0, 10), iv(12, 30)]
    );
}

#[test]
fn returns_empty_for_gap_only_query() {
    let set = build([(10, 20), (30, 40)]);
    let query = iv(20, 30);

    assert_eq!(
        set.intervals_intersecting(query).collect::<Vec<_>>(),
        vec![]
    );
}

#[test]
fn handles_domain_edges() {
    let set = build([(i128::MIN, i128::MIN + 1), (i128::MAX - 1, i128::MAX)]);

    assert_eq!(
        set.intervals_intersecting(iv(i128::MIN, i128::MIN + 1))
            .collect::<Vec<_>>(),
        vec![iv(i128::MIN, i128::MIN + 1)]
    );
    assert_eq!(
        set.intervals_intersecting(iv(i128::MAX - 1, i128::MAX))
            .collect::<Vec<_>>(),
        vec![iv(i128::MAX - 1, i128::MAX)]
    );
}

#[test]
fn representative_queries_match_intersection_predicate() {
    let set = build([(10, 20), (30, 40), (50, 60)]);

    for query in [
        iv(0, 10),
        iv(9, 11),
        iv(15, 35),
        iv(20, 30),
        iv(39, 41),
        iv(40, 50),
        iv(55, 61),
        iv(i128::MAX - 1, i128::MAX),
    ] {
        assert_eq!(
            set.intervals_intersecting(query).next().is_some(),
            set.intersects_interval(query),
            "query = {query:?}"
        );
    }
}

proptest! {
    #[test]
    fn prop_matches_slice_filter(
        xs in prop::collection::vec(arb_iv(), 0..64),
        query in arb_iv(),
    ) {
        let set: I128COSet = xs.into_iter().collect();

        let got = set.intervals_intersecting(query).collect::<Vec<_>>();
        let expected = set
            .as_slice()
            .iter()
            .copied()
            .filter(|iv| iv.intersects(query))
            .collect::<Vec<_>>();

        prop_assert_eq!(got, expected);
    }

    #[test]
    fn prop_non_empty_result_matches_predicate(
        xs in prop::collection::vec(arb_iv(), 0..64),
        query in arb_iv(),
    ) {
        let set: I128COSet = xs.into_iter().collect();

        prop_assert_eq!(
            set.intervals_intersecting(query).next().is_some(),
            set.intersects_interval(query)
        );
    }
}
